import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync} from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';
process.env.NODE_ENV='test';process.env.DATA_DIR=mkdtempSync(path.join(tmpdir(),'choirloom-chat-'));process.env.APP_ORIGIN='http://localhost:5173';
const {createHttpServer}=await import('../server/index.ts'),{run,one,revision}=await import('../server/db.ts'),{homes}=await import('../server/ai.ts');writeFileSync(path.join(homes(),'auth.json'),'{}');const server=createHttpServer();server.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const root=`http://127.0.0.1:${(server.address() as any).port}/api`;test.after(()=>new Promise<void>(r=>server.close(()=>r())));
let cookie='',csrf='';async function req(url:string,body?:any){const r=await fetch(root+url,{method:body?'POST':'GET',headers:{origin:process.env.APP_ORIGIN!,cookie,'x-csrf-token':csrf,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(r.headers.get('set-cookie')){cookie=r.headers.get('set-cookie')!.split(';')[0];csrf=data.csrf;}return {status:r.status,data};}
test('new chats preserve history; rewind restores prompt and score; retry replaces turns with a fresh job',async()=>{
 const u=(await req('/auth/signup',{email:'chat@example.com',name:'Chat',password:'a-long-test-password'})).data.user;const p=(await req('/projects',{demo:true})).data;const first=(await req(`/projects/${p.id}`)).data;const body={prompt:'Make it gentle',mode:'revise',effort:'high',locale:'en',conversationId:first.chatId};const job=(await req(`/projects/${p.id}/ai`,body)).data;assert(job.id);assert.equal((await req(`/projects/${p.id}/chats`,{})).status,409);
 run("UPDATE jobs SET status='complete' WHERE id=?",job.id);const original=JSON.parse(one('SELECT score FROM projects WHERE id=?',p.id).score),changed={...original,title:'Changed'};revision(one('SELECT * FROM projects WHERE id=?',p.id),changed,u.id);run("INSERT INTO chats(id,project_id,user_id,role,content,job_id,revision,conversation_id) VALUES('reply',?,?,'assistant','Done',?,2,?)",p.id,u.id,job.id,first.chatId);run("UPDATE chat_sessions SET thread_id='stale-remote-thread' WHERE id=?",first.chatId);
 const fresh=(await req(`/projects/${p.id}/chats`,{})).data;assert.notEqual(fresh.id,first.chatId);let detail=(await req(`/projects/${p.id}`)).data;assert.equal(detail.chats.length,0);assert.equal(detail.score.title,'Changed');assert.equal(detail.chatSessions.length,2);
 await req(`/projects/${p.id}/chats/${first.chatId}/activate`,{});detail=(await req(`/projects/${p.id}`)).data;assert.equal(detail.chats.length,2);const prompt=detail.chats[0];const rewind=await req(`/projects/${p.id}/chats/rewind/${prompt.id}`,{version:2});assert.equal(rewind.status,200,JSON.stringify(rewind.data));assert.equal(rewind.data.restored.effort,'high');detail=(await req(`/projects/${p.id}`)).data;assert.equal(detail.chats.length,0);assert.equal(detail.score.title,original.title);assert.equal(detail.view.draft,body.prompt);assert.equal(one('SELECT thread_id FROM chat_sessions WHERE id=?',first.chatId).thread_id,null);assert.equal(one('SELECT id FROM jobs WHERE id=?',job.id),undefined);assert.equal(detail.version,3);
 const next=(await req(`/projects/${p.id}/ai`,body)).data;run("UPDATE jobs SET status='failed' WHERE id=?",next.id);detail=(await req(`/projects/${p.id}`)).data;const retry=await req(`/projects/${p.id}/chats/rewind/${detail.chats[0].id}`,{version:3,retry:true});assert.equal(retry.status,200);assert(retry.data.job.id);detail=(await req(`/projects/${p.id}`)).data;assert.equal(detail.chats.length,1);assert.equal(detail.chats[0].job_id,retry.data.job.id);assert.equal(detail.view.draft,'');assert.equal((await req(`/projects/${p.id}/chats/rewind/${detail.chats[0].id}`,{version:1})).status,409);
});
