import test from 'node:test';import assert from 'node:assert/strict';
import {demoScore,toMusicXML,fromMusicXML,toMXL,readMXL,validateScore,wordlessLyrics} from '../shared/music.ts';
test('MusicXML and MXL round trips preserve notes, rhythms and lyric syllables',()=>{const source=demoScore();for(const xml of [toMusicXML(source),readMXL(toMXL(source))]){const restored=fromMusicXML(xml);assert.equal(restored.title,source.title);assert.deepEqual(restored.parts[0].notes.map(({pitch,start,duration,lyric})=>({pitch,start,duration,lyric})),source.parts[0].notes.map(({pitch,start,duration,lyric})=>({pitch,start,duration,lyric})));}});
test('validator rejects overlap and changes to the original melody',()=>{const source=demoScore(),changed=structuredClone(source);changed.parts[0].notes[1].start=1;changed.parts[0].notes[0].pitch=61;const errors=validateScore(changed,source);assert(errors.some(e=>e.code==='overlap'));assert(errors.some(e=>e.code==='leadChanged'));});
test('wordless patterns preserve authored lyrics and skip tied-note attacks',()=>{const p=demoScore().parts[0];p.wordless='ba';p.notes.forEach(n=>n.lyric='');p.notes[0].lyric='hello';p.notes[2].tie='stop';const result=wordlessLyrics(p);assert.equal(result.get(p.notes[0].id),'hello');assert.equal(result.get(p.notes[1].id),'ba');assert.equal(result.get(p.notes[2].id),'');});
test('unsafe XML entity declarations are rejected',()=>assert.throws(()=>fromMusicXML('<!DOCTYPE x [<!ENTITY a SYSTEM "file:///etc/passwd">]><score-partwise/>')));

import {validateScopedEdit} from '../shared/edit-scope.ts';
test('bar-scoped edits preserve outside notes, crossing notes, other voices and metadata',()=>{const before=demoScore(),after=structuredClone(before);after.parts[0].notes[5].pitch=63;assert.deepEqual(validateScopedEdit(before,after,{startBar:2,endBar:2}),[]);assert(validateScopedEdit(before,after,{startBar:1,endBar:1}).length);after.tempo=100;assert(validateScopedEdit(before,after,{startBar:2,endBar:2}).length);const crossing=structuredClone(before);crossing.parts[0].notes[3].duration=960;const changed=structuredClone(crossing);changed.parts[0].notes[3].pitch=63;assert(validateScopedEdit(crossing,changed,{startBar:2,endBar:2}).length);assert(validateScopedEdit(before,after,{startBar:2,endBar:2,partIds:['another-voice']}).length);});
test('new composition and revisions may change the lead but never locked notes',()=>{const before=demoScore(),after=structuredClone(before);after.parts[0].notes[0].pitch=62;assert(validateScore(after,before).some(f=>f.code==='leadChanged'));assert(!validateScore(after,before,false).some(f=>f.code==='leadChanged'));before.parts[0].notes[0].locked=true;assert(validateScore(after,before,false).some(f=>f.code==='lockedChanged'));});
test('woooo has a sustained underlay, preserves lyrics, and survives structured export',()=>{const score=demoScore();score.parts[0].wordless='woo';score.parts[0].notes[1].lyric='';const lyrics=wordlessLyrics(score.parts[0]);assert.equal(lyrics.get(score.parts[0].notes[1].id),'woo');assert.equal(lyrics.get(score.parts[0].notes[0].id),'mor');assert(toMusicXML(score,true).includes('<text>woo</text>'));});
