import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {WebSocket} from 'ws';
process.env.NODE_ENV='test';process.env.DATA_DIR=mkdtempSync(path.join(tmpdir(),'choirloom-live-'));process.env.APP_ORIGIN='http://localhost:5173';process.env.SCORE_LIBRARY_MANIFEST=path.join(process.env.DATA_DIR,'score-library.json');process.env.VOICEBANK_MANIFEST=path.join(process.env.DATA_DIR,'voicebanks.json');writeFileSync(process.env.VOICEBANK_MANIFEST,'[]');
const {createHttpServer}=await import('../server/index.ts'),{run,one}=await import('../server/db.ts'),{log,logs}=await import('../server/diagnostics.ts');const server=createHttpServer();server.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const root=`http://127.0.0.1:${(server.address() as any).port}`,sockets:WebSocket[]=[];
test.after(async()=>{for(const ws of sockets)ws.terminate();await new Promise<void>(r=>server.close(()=>r()));});
async function request(url:string,method='GET',body?:any,account?:any){const r=await fetch(root+'/api'+url,{method,headers:{origin:process.env.APP_ORIGIN!,cookie:account?.cookie||'','x-csrf-token':account?.csrf||'','content-type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function account(email:string){const r=await request('/auth/signup','POST',{email,name:email.split('@')[0],password:'a long test password'});assert.equal(r.status,201);return {id:r.data.user.id,cookie:r.cookie,csrf:r.data.csrf};}
async function live(a:any,projectId:string|null=null,admin=false){const ws=new WebSocket(root.replace('http:','ws:')+'/api/live',{headers:{origin:process.env.APP_ORIGIN!,cookie:a.cookie}});sockets.push(ws);const messages:any[]=[],waiting=new Set<()=>void>();ws.on('message',raw=>{messages.push(JSON.parse(raw.toString()));for(const fn of waiting)fn();});await new Promise<void>((r,j)=>{ws.once('open',r);ws.once('error',j);});const wait=(type:string,predicate=(data:any)=>true)=>new Promise<any>((resolve,reject)=>{const timeout=setTimeout(()=>{waiting.delete(check);reject(Error('Missing '+type));},5000);const check=()=>{const i=messages.findIndex(m=>m.type===type&&predicate(m.data));if(i>=0){const [message]=messages.splice(i,1);clearTimeout(timeout);waiting.delete(check);resolve(message.data);}};waiting.add(check);check();});ws.send(JSON.stringify({type:'subscribe',csrf:a.csrf,projectId,admin}));await wait('session');return {ws,messages,wait};}
const a=await account('first@example.com'),b=await account('second@example.com'),c=await account('third@example.com');run("UPDATE users SET role='admin' WHERE id=?",a.id);const p=(await request('/projects','POST',{demo:true},b)).data;
test('WebSocket snapshots, mutation pushes, access revocation and client diagnostics',async()=>{
 const owner=await live(b,p.id),admin=await live(a,p.id,true);assert.equal((await owner.wait('project')).role,'owner');assert.equal((await admin.wait('project')).role,'viewer');assert.equal((await admin.wait('admin')).users.length,3);
 assert.equal((await request('/admin','GET',undefined,c)).status,403);assert.equal((await request(`/projects/${p.id}`,'GET',undefined,c)).status,403);
 run("INSERT INTO jobs(id,project_id,user_id,kind,status,payload) VALUES('push-job',?,?,'ai','queued','{}')",p.id,b.id);await owner.wait('jobs',d=>d.jobs.some((j:any)=>j.id==='push-job'&&j.status==='queued'));
 owner.ws.close();run("UPDATE jobs SET status='failed',stage='failed',error='aiFailed' WHERE id='push-job'");const resumed=await live(b,p.id);const snapshot=await resumed.wait('project');assert.equal(snapshot.jobs[0].status,'failed');assert.equal(snapshot.jobs[0].stage,'failed');
 const batch={clientId:'browser-test',events:[{id:'event-1',time:new Date().toISOString(),level:'error',event:'test.failed',message:'Bearer abcsecret',context:{password:'do-not-store',prompt:'private words',jobId:'push-job'}}]};resumed.ws.send(JSON.stringify({type:'client.logs',csrf:b.csrf,batch}));assert.deepEqual((await resumed.wait('logs.ack')).accepted,['event-1']);resumed.ws.send(JSON.stringify({type:'client.logs',csrf:b.csrf,batch}));await resumed.wait('logs.ack');const entries=logs({jobId:'push-job',source:'client'});assert.equal(entries.length,1);assert(!JSON.stringify(entries).includes('abcsecret'));assert(!JSON.stringify(entries).includes('do-not-store'));assert(!JSON.stringify(entries).includes('private words'));await admin.wait('log',d=>d.source==='client');
 assert.equal((await request('/client-logs','POST',{...batch,csrf:'wrong'},b)).status,403);
 assert.equal((await request(`/admin/users/${c.id}/role`,'PATCH',{role:'admin'},a)).status,200);const promoted=await live(c,null,true);assert((await promoted.wait('admin')).works.some((w:any)=>w.id===p.id));
 assert.equal((await request(`/admin/users/${a.id}/role`,'PATCH',{role:'user'},c)).status,200);await admin.wait('session',u=>u.role==='user');await admin.wait('project.denied');log('error','admin.secret',{userId:c.id});assert.equal((await request('/admin','GET',undefined,a)).status,403);
 assert.equal((await request(`/admin/users/${c.id}/role`,'PATCH',{role:'user'},c)).data.error,'lastAdmin');
});
test('WebSocket rejects wrong origins, missing sessions and invalid CSRF',async()=>{
 for(const [cookie,origin,status] of [[b.cookie,'https://evil.example',403],['',process.env.APP_ORIGIN,401]] as const){await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(root.replace('http:','ws:')+'/api/live',{headers:{cookie:cookie||'',origin:origin!}});ws.on('unexpected-response',(_req,res)=>{try{assert.equal(res.statusCode,status);res.resume();resolve();}catch(e){reject(e);}ws.terminate();});ws.on('error',()=>{});});}
 const ws=new WebSocket(root.replace('http:','ws:')+'/api/live',{headers:{origin:process.env.APP_ORIGIN!,cookie:b.cookie}});sockets.push(ws);await new Promise<void>(r=>ws.once('open',r));const closed=new Promise<number>(r=>ws.once('close',r));ws.send(JSON.stringify({type:'subscribe',csrf:'wrong'}));assert.equal(await closed,4403);
});
test('references persist, support PDF/images/text, enforce ownership and bind idempotent chat requests',async()=>{
 async function upload(file:Blob,name:string,actor=b){const form=new FormData();form.append('file',file,name);const r=await fetch(root+`/api/projects/${p.id}/references`,{method:'POST',headers:{origin:process.env.APP_ORIGIN!,cookie:actor.cookie!,'x-csrf-token':actor.csrf},body:form});return {status:r.status,data:await r.json()};}
 const text=await upload(new Blob(['Use warm close harmony.']),'style notes.txt');assert.equal(text.status,200);const ref=text.data[0];assert.equal(ref.mention,'style_notes.txt');assert.equal((await upload(new Blob(['copy']),'style notes.txt')).data[1].mention,'style_notes.txt-2');assert.equal((await upload(new Blob(['bad']),'script.exe')).data.error,'referenceType');assert.equal((await upload(new Blob(['private']),'notes.txt',a)).status,403);
 const {jsPDF}=await import('jspdf'),pdf=new jsPDF();pdf.text('Reference score notes',20,20);const document=await upload(new Blob([pdf.output('arraybuffer')]),'score.pdf');assert.equal(document.status,200,JSON.stringify(document.data));const pdfRow=one('SELECT * FROM references_files WHERE id=?',document.data.at(-1).id);assert(pdfRow.text.includes('Reference score notes'));assert.equal(JSON.parse(pdfRow.images).length,1);
 const {createCanvas}=await import('@napi-rs/canvas');const canvas=createCanvas(50,50);const png=await upload(new Blob([new Uint8Array(canvas.toBuffer('image/png'))]),'melody.png');assert.equal(png.status,200);
 const {referenceInput}=await import('../server/references.ts');assert.equal(referenceInput(p.id,{id:b.id,verified:1,email:'second@example.com'},[pdfRow.id]).filter(i=>i.type==='local_image').length,1);
 assert.equal((await request('/references/'+ref.id,'GET',undefined,a)).status,403);
 const {homes}=await import('../server/ai.ts');writeFileSync(path.join(homes(),'auth.json'),'{}');const body={prompt:'Use @style_notes.txt',effort:'medium',locale:'en',mode:'chat',referenceIds:[ref.id],requestId:crypto.randomUUID()};const first=await request(`/projects/${p.id}/ai`,'POST',body,b),duplicate=await request(`/projects/${p.id}/ai`,'POST',body,b);assert.equal(first.status,200);assert.equal(duplicate.data.id,first.data.id);assert.equal(one('SELECT COUNT(*) AS count FROM chats WHERE request_id=?',body.requestId).count,1);
 const persisted=(await request(`/projects/${p.id}`,'GET',undefined,b)).data;assert.equal(persisted.chats.at(-1).job_id,first.data.id);assert.deepEqual(JSON.parse(persisted.chats.at(-1).reference_ids),[ref.id]);assert.equal(persisted.references.length,4);run("UPDATE jobs SET status='cancelled' WHERE id=?",first.data.id);
 const forged=await request(`/projects/${p.id}/ai`,'POST',{...body,requestId:crypto.randomUUID(),referenceIds:['unknown']},b);assert.equal(forged.status,404);
});
test('song library imports a vocal melody as a new private work with attribution',async()=>{
 const {mkdirSync}=await import('node:fs'),{demoScore,toMXL}=await import('../shared/music.ts'),{createHash}=await import('node:crypto');const bytes=toMXL(demoScore()),sha=createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');mkdirSync(path.join(process.env.DATA_DIR!,'score-library'));writeFileSync(path.join(process.env.DATA_DIR!,'score-library',sha+'.mxl'),bytes);writeFileSync(process.env.SCORE_LIBRARY_MANIFEST!,JSON.stringify({sourceUrl:'https://github.com/OpenScore/Lieder',licenseUrl:'https://github.com/OpenScore/Lieder',songs:[{id:'test-song',title:'Test song',composer:'Test composer',languages:['en'],source:'OpenScore Lieder',license:'CC0-1.0',sourceUrl:'https://github.com/OpenScore/Lieder',url:'https://raw.githubusercontent.com/OpenScore/Lieder/main/test.mxl',blobSha:sha}]}));
 const catalog=await request('/library');assert.equal(catalog.data.songs.length,1);assert(!('url' in catalog.data.songs[0]));const preview=await request('/library/test-song','GET',undefined,b);assert.equal(preview.status,200);assert.equal(preview.data.parts.length,1);assert(preview.data.score.parts[0].notes.some((n:any)=>n.lyric));const imported=await request('/library/test-song/import','POST',{part:preview.data.selectedPart},b);assert.equal(imported.status,200);assert.equal((await request(`/projects/${imported.data.id}`,'GET',undefined,a)).status,403);const details=(await request(`/projects/${imported.data.id}`,'GET',undefined,b)).data;assert.equal(JSON.parse(details.source).license,'CC0-1.0');assert.equal(details.score.composer,'Test composer');
 const compose=await request(`/projects/${imported.data.id}/ai`,'POST',{mode:'compose',prompt:'Compose an original song with lyrics',effort:'medium',locale:'en'},b);assert.equal(compose.status,200);run("UPDATE jobs SET status='cancelled' WHERE id=?",compose.data.id);
 const invalid=await request(`/projects/${imported.data.id}/ai`,'POST',{mode:'revise',prompt:'Change only these bars',effort:'medium',locale:'en',selection:{startBar:2,endBar:1}},b);assert.equal(invalid.data.error,'invalidBarSelection');
});
test('event-driven queue consumes jobs and persists terminal state without a connected browser',async()=>{
 const {startWorker,createJob}=await import('../server/jobs.ts'),{events}=await import('../server/events.ts');startWorker();const completion=(id:string)=>new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>{events.off('change',check);reject(Error('Worker did not finish'));},5000);function check(){if(one('SELECT status FROM jobs WHERE id=?',id)?.status==='failed'){clearTimeout(timeout);events.off('change',check);resolve();}}events.on('change',check);check();});
 const j=createJob({id:p.id,version:1},{id:b.id},'unknown',{});await completion(j.id);assert.equal(one('SELECT stage FROM jobs WHERE id=?',j.id).stage,'failed');const next=createJob({id:p.id,version:1},{id:b.id},'unknown',{});await completion(next.id);assert(logs({jobId:next.id}).some(l=>l.event==='job.failed'));
});
