import test from 'node:test';
import assert from 'node:assert/strict';
import {newScore,toMusicXML,fromMusicXML,barTicks,endTick,singingKey} from '../shared/music.ts';
import {playbackBars,expandRepeats} from '../shared/repeats.ts';
import {playbackDuration} from '../src/audio.ts';
function fixture(){const s=newScore('Repeat study');s.beats=3;s.parts[0].notes=Array.from({length:5},(_,i)=>({id:'n'+i,pitch:60+i,start:i*1440,duration:1440,lyric:'',syllabic:'single' as const,tie:'none' as const,locked:false}));s.barlines=[{bar:3,location:'left',endingType:'start',endingNumbers:[1]},{bar:3,location:'right',repeat:'backward',endingType:'stop',endingNumbers:[1]},{bar:4,location:'left',endingType:'start',endingNumbers:[2]},{bar:5,location:'right',endingType:'discontinue',endingNumbers:[2]}];return s;}
test('repeat and alternate endings survive import/export without duplicating written notes',()=>{const s=fixture(),xml=toMusicXML(s),restored=fromMusicXML(xml);assert.equal(restored.parts[0].notes.filter(n=>n.pitch!==null).length,5);assert.deepEqual(playbackBars(restored),[1,2,3,1,2,4,5]);assert.match(toMusicXML(restored),/<repeat direction="backward"/);assert.match(toMusicXML(restored),/<ending number="2" type="start"/);});
test('performance visits first ending once, skips it on second pass, and leaves written score unchanged',()=>{const s=fixture(),before=JSON.stringify(s),performed=expandRepeats(s);assert.deepEqual(performed.parts[0].notes.map(n=>n.pitch),[60,61,62,60,61,63,64]);assert.equal(endTick(performed),7*barTicks(s));assert(Math.abs(playbackDuration(s)-7*3*60/s.tempo)<1e-8);assert.equal(JSON.stringify(s),before);assert.notEqual(singingKey(s),singingKey({...s,barlines:[]}));});
test('explicit repeat starts and repeat counts bound playback to the specified passage',()=>{const s=fixture();s.barlines=[{bar:2,location:'left',repeat:'forward'},{bar:3,location:'right',repeat:'backward',times:3}];assert.deepEqual(playbackBars(s),[1,2,3,2,3,2,3,4,5]);});
