import test from 'node:test';import assert from 'node:assert/strict';import {fromMusicXML,validateScore,type Finding} from '../shared/music.ts';
const wrap=(notes:string)=>`<score-partwise><part-list><score-part id="P1"><part-name>Voice</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>480</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${notes}</measure></part></score-partwise>`;
const note=(step:string,extra='',voice=1)=>`<note>${extra}<pitch><step>${step}</step><octave>4</octave></pitch><duration>480</duration><voice>${voice}</voice><lyric><text>${step}</text></lyric></note>`;
test('chords preserve simultaneous onset and following-note timing in separate parts',()=>{const findings:Finding[]=[];const s=fromMusicXML(wrap(note('C')+note('E','<chord/>')+note('D')),undefined,findings);assert.equal(s.parts.length,2);assert.deepEqual(s.parts.flatMap(p=>p.notes).filter(n=>n.pitch!==null).map(n=>[n.pitch,n.start,n.lyric]),[[60,0,'C'],[62,480,'D'],[64,0,'E']]);assert(findings.some(f=>f.code==='importSplitVoices'));assert.equal(validateScore(s).filter(f=>f.severity==='error').length,0);});
test('separate MusicXML voices remain separate across backup and forward',()=>{const s=fromMusicXML(wrap(note('C','',1)+'<backup><duration>480</duration></backup><forward><duration>480</duration></forward>'+note('G','',2)));assert.equal(s.parts.length,2);assert.equal(s.parts[1].notes[0].start,480);});
test('duplicate rests are merged and overlapping rests never cover melody notes',()=>{const s=fromMusicXML(wrap('<note><rest/><duration>1920</duration></note><backup><duration>1920</duration></backup><note><rest/><duration>480</duration></note>'+note('C')));assert.deepEqual(s.parts[0].notes.map(n=>[n.pitch,n.start,n.duration]),[[null,0,480],[60,480,480],[null,960,960]]);assert.equal(validateScore(s).filter(f=>f.severity==='error').length,0);});
test('unmatched ties are reported and repaired without changing notes or lyrics',()=>{const findings:Finding[]=[];const s=fromMusicXML(wrap(note('C','<tie type="start"/>')+note('D')),undefined,findings);assert.equal(s.parts[0].notes[0].tie,'none');assert(findings.some(f=>f.code==='importTieRepaired'));assert.equal(validateScore(s).filter(f=>f.severity==='error').length,0);});

test('the pinned Summer At Last catalog score imports without external editing',async()=>{const {readFileSync}=await import('node:fs');const {readMXL}=await import('../shared/music.ts');const score=fromMusicXML(readMXL(readFileSync(new URL('./fixtures/summer-at-last.mxl',import.meta.url))),['P1']);assert.equal(score.parts.length,1);assert.equal(score.parts[0].notes.filter(n=>n.pitch!==null).length,253);assert(score.parts[0].notes.some(n=>n.lyric==='blue,'));assert.equal(validateScore(score).filter(f=>f.severity==='error').length,0);});

test('sequential source voices beyond the studio limit are packed without losing notes',()=>{const findings:Finding[]=[];const s=fromMusicXML(wrap(Array.from({length:25},(_,i)=>note('C','',i+1)).join('')),undefined,findings);assert.equal(s.parts.length,1);assert.equal(s.parts[0].notes.filter(n=>n.pitch!==null).length,25);assert.equal(s.parts[0].notes.at(-1)!.start,24*480);assert(findings.some(f=>f.code==='importPackedVoices'));assert.equal(validateScore(s).filter(f=>f.severity==='error').length,0);});
