import test from 'node:test';import assert from 'node:assert/strict';
import {inspectTranscription,mergeSheets,proofImages,pageImages} from '../server/score-recognition.ts';
import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';
import {fromMusicXML} from '../shared/music.ts';
import {compactToXML,type CompactPage} from '../server/compact-score.ts';
const sheet=(pitch='C')=>`<score-partwise version="4.0"><part-list><score-part id="P1"><part-name>Voice</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>3</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>${pitch}</step><octave>4</octave></pitch><duration>3</duration></note></measure></part></score-partwise>`;
test('transcription validator catches wrong meter duration and unsafe XML',()=>{assert.deepEqual(inspectTranscription(sheet()),[]);assert.match(inspectTranscription(sheet().replace('<duration>3','<duration>4'))[0],/expected 3/);assert(inspectTranscription('<!ENTITY bad "x">'+sheet()).length);});
test('page assembly preserves part order and written measure sequence',()=>{const xml=mergeSheets([sheet(),sheet('D')]),s=fromMusicXML(xml);assert.deepEqual(s.parts[0].notes.map(n=>[n.start,n.pitch]),[[0,60],[1440,62]]);assert.match(xml,/<measure number="2">/);assert.throws(()=>mergeSheets([sheet(),sheet().replaceAll('P1','P2')]));});
test('verification actually engraves MusicXML into a raster proof for the model',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'choirloom-proof-')),images=await proofImages(sheet(),dir,1);assert(images.length);const file=images[0];assert.equal(file.type,'local_image');if(file.type==='local_image')assert.equal(readFileSync(file.path).subarray(1,4).toString(),'PNG');});
test('TIFF sheets are decoded into model-readable PNGs',async()=>{const UTIF=(await import('utif')).default,dir=mkdtempSync(path.join(tmpdir(),'choirloom-tiff-')),file=path.join(dir,'score.tif');writeFileSync(file,Buffer.from(UTIF.encodeImage(new Uint8Array(16).fill(255),2,2)));const pages=await pageImages(file,dir,new AbortController().signal);assert.equal(pages.length,1);assert.equal(readFileSync(pages[0]).subarray(1,4).toString(),'PNG');});
test('compact visual data generates faithful lyrics, accidentals and repeats without XML boilerplate',()=>{
 const page:CompactPage={title:'Study',composer:'',beats:3,beatType:'4',key:-1,tempo:null,tempoWords:'Slowly',parts:[{id:'P1',name:'Voice',clef:'G',clefLine:2,measures:[{pickup:false,directions:'',notes:[['Bb4',960,'Sing','single','none',''],['A4',480,'& rest','single','none','']]}]}],barlines:[{bar:1,location:'right',repeat:'backward',times:2,ending:'none',numbers:[]}]};
 const xml=compactToXML(page);assert.deepEqual(inspectTranscription(xml),[]);assert.match(xml,/<alter>-1<\/alter>/);assert.match(xml,/<words>Slowly<\/words>/);assert(!xml.includes('<per-minute>'));assert.match(xml,/<repeat direction="backward"/);const s=fromMusicXML(xml);assert.deepEqual(s.parts[0].notes.map(n=>[n.pitch,n.lyric]),[[70,'Sing'],[69,'& rest']]);
});

