import {z} from 'zod';
const cell=z.union([z.string(),z.number()]);
/** A compact visual transcript; the harness, not the model, writes XML boilerplate. */
export const compactPageSchema=z.object({title:z.string().max(200),composer:z.string().max(200),beats:z.number().int().min(1).max(16),beatType:z.enum(['2','4','8','16']),key:z.number().int().min(-7).max(7),tempo:z.number().min(20).max(300).nullable(),tempoWords:z.string().max(200),parts:z.array(z.object({id:z.string().regex(/^[A-Za-z][A-Za-z0-9_-]*$/),name:z.string().max(80),clef:z.enum(['G','F','C']),clefLine:z.number().int().min(1).max(5),measures:z.array(z.object({pickup:z.boolean(),notes:z.array(z.array(cell).length(6)).max(200),directions:z.string().max(8000)})).min(1).max(300)})).min(1).max(24),barlines:z.array(z.object({bar:z.number().int().min(1).max(300),location:z.enum(['left','right']),repeat:z.enum(['none','forward','backward']),times:z.number().int().min(2).max(8),ending:z.enum(['none','start','stop','discontinue']),numbers:z.array(z.number().int().min(1).max(8))})).max(100)});
export type CompactPage=z.infer<typeof compactPageSchema>;
const escape=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
function durationType(ticks:number){for(const [n,type] of [[1920,'whole'],[960,'half'],[480,'quarter'],[240,'eighth'],[120,'16th'],[60,'32nd'],[30,'64th']] as const){if(ticks===n)return `<type>${type}</type>`;if(ticks===n*1.5)return `<type>${type}</type><dot/>`;}return '';}
export function compactToXML(input:CompactPage):string{
 const s=compactPageSchema.parse(input),count=s.parts[0].measures.length;if(s.parts.some(p=>p.measures.length!==count)||s.barlines.some(b=>b.bar>count))throw Error('invalidImport');
 const marks=(bar:number,location:string)=>s.barlines.filter(b=>b.bar===bar&&b.location===location).map(b=>`<barline location="${location}">${b.ending!=='none'?`<ending number="${b.numbers.join(',')}" type="${b.ending}"/>`:''}${b.repeat!=='none'?`<repeat direction="${b.repeat}" times="${b.times}"/>`:''}</barline>`).join('');
 return `<?xml version="1.0" encoding="utf-8"?><score-partwise version="4.0"><work><work-title>${escape(s.title)}</work-title></work><identification><creator type="composer">${escape(s.composer)}</creator></identification><part-list>${s.parts.map(p=>`<score-part id="${p.id}"><part-name>${escape(p.name)}</part-name></score-part>`).join('')}</part-list>${s.parts.map(p=>`<part id="${p.id}">${p.measures.map((m,i)=>`<measure number="${i+1}"${m.pickup?' implicit="yes"':''}>${i===0?`<attributes><divisions>480</divisions><key><fifths>${s.key}</fifths></key><time><beats>${s.beats}</beats><beat-type>${s.beatType}</beat-type></time><clef><sign>${p.clef}</sign><line>${p.clefLine}</line></clef></attributes>${s.tempoWords?`<direction><direction-type><words>${escape(s.tempoWords)}</words></direction-type></direction>`:''}${s.tempo?`<direction><direction-type><metronome><beat-unit>quarter</beat-unit><per-minute>${s.tempo}</per-minute></metronome></direction-type><sound tempo="${s.tempo}"/></direction>`:''}`:''}${marks(i+1,'left')}${m.directions}${m.notes.map(row=>{
 const [pitch,duration,lyric,syllabic,tie,extra]=row;if(typeof pitch!=='string'||typeof duration!=='number'||!Number.isInteger(duration)||duration<=0||typeof lyric!=='string'||typeof extra!=='string'||!['single','begin','middle','end'].includes(String(syllabic))||!['none','start','stop','continue'].includes(String(tie)))throw Error('invalidImport');
 const match=/^([A-G])([#b]{0,2})(-?\d)$/.exec(pitch);if(pitch!=='R'&&!match)throw Error('invalidImport');const alter=match?.[2].includes('#')?match[2].length:-(match?.[2].length||0),stop=['stop','continue'].includes(String(tie)),start=['start','continue'].includes(String(tie));
 return `<note>${pitch==='R'?'<rest/>':`<pitch><step>${match![1]}</step>${alter?`<alter>${alter}</alter>`:''}<octave>${match![3]}</octave></pitch>`}<duration>${duration}</duration>${stop?'<tie type="stop"/>':''}${start?'<tie type="start"/>':''}${/<type>/.test(extra)?'':durationType(duration)}${start||stop?`<notations>${stop?'<tied type="stop"/>':''}${start?'<tied type="start"/>':''}</notations>`:''}${extra}${lyric?`<lyric><syllabic>${syllabic}</syllabic><text>${escape(lyric)}</text></lyric>`:''}</note>`;
 }).join('')}${marks(i+1,'right')}</measure>`).join('')}</part>`).join('')}</score-partwise>`;
}
