import {rasterizeScoreSvg} from './svg-import.ts';
import {currentChat,switchChat,rewindChat} from './chats.ts';
import {libraryCatalog,libraryScore} from './library.ts';
import {preferredLocale} from '../shared/locale.ts';
import {addReference,referenceFile,resolveReferences} from './references.ts';
import express from 'express';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {attachRealtime} from './realtime.ts';
import {safeUser,projectList,projectDetails} from './projects.ts';
import {log,logs,ingestClientLogs} from './diagnostics.ts';
import {adminSnapshot,setRole} from './admin.ts';
import {telemetrySchema} from '../shared/telemetry.ts';
import {changed} from './events.ts';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import {rateLimit,ipKeyGenerator} from 'express-rate-limit';
import {isIP} from 'node:net';
import multer from 'multer';
import argon2 from 'argon2';
import {z} from 'zod';
import path from 'node:path';
import {existsSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import midiPackage from '@tonejs/midi';
const {Midi}=midiPackage;
import {all,one,run,dataDir,token,hash,emailKey,transaction,HttpError,access,revision} from './db.ts';
import {scoreSchema,validateScore,newScore,demoScore,uid,toMusicXML,toMXL,fromMusicXML,readMXL,createPart,PPQ,barTicks,endTick,type Score} from '../shared/music.ts';
import {sendMail,sendToken,origin} from './mail.ts';
import {connected,startLogin,loginStatus,stopLogin,homes,efforts} from './ai.ts';
import {createJob,cancelJob,capabilities,startWorker} from './jobs.ts';
import {selection,structuredExport,audioExport} from './exports.ts';
import {voiceState,startVoiceInstall,removeVoice,requireVoices,recoverVoiceInstalls} from './voicebanks.ts';
import {startVoiceImport,recoverVoiceImports} from './voice-imports.ts';
export const app=express();const prod=process.env.NODE_ENV==='production';
// IISNode transports HTTP over a named pipe, so socket.remoteAddress is absent.
// Azure appends the actual client as the last forwarded address.
const clientKey=(req:express.Request)=>{const remote=req.socket.remoteAddress;const forwarded=(!remote||['127.0.0.1','::1','::ffff:127.0.0.1'].includes(remote))?req.get('x-forwarded-for')?.split(',').at(-1)?.trim():undefined;let value=forwarded||remote||'unknown-client';if(/^\[.+\]:\d+$/.test(value))value=value.slice(1,value.lastIndexOf(']'));else if(/^\d+\.\d+\.\d+\.\d+:\d+$/.test(value))value=value.split(':')[0];return isIP(value)?ipKeyGenerator(value):'unknown-client';};
app.use((req,_res,next)=>{const base=process.env.APP_BASE;if(base&&(req.url===base||req.url.startsWith(base+'/')))req.url=req.url.slice(base.length)||'/';next();});
app.use('/api',(req,res,next)=>{res.locals.requestId=randomUUID();res.setHeader('X-Request-Id',res.locals.requestId);const start=performance.now();res.on('finish',()=>{if(req.originalUrl.split('?')[0].endsWith('/client-logs'))return;log(res.statusCode>=500?'error':res.statusCode>=400?'warn':'debug','http.response',{requestId:res.locals.requestId,userId:res.locals.user?.id,method:req.method,path:req.path,status:res.statusCode,durationMs:Math.round(performance.now()-start)});});next();});
app.set('trust proxy','loopback');app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{'script-src':["'self'","'wasm-unsafe-eval'"],'img-src':["'self'",'data:','blob:'],'media-src':["'self'",'blob:'],'style-src':["'self'","'unsafe-inline'"],'connect-src':["'self'"],'object-src':["'none'"]}},crossOriginEmbedderPolicy:false}));app.use(express.json({limit:'4mb'}));app.use(cookieParser());
app.use('/api',rateLimit({keyGenerator:clientKey,windowMs:60000,limit:240,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'rateLimited'}}));
app.use('/api',(req,res,next)=>{res.setHeader('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.get('origin')!==origin)return res.status(403).json({error:'origin'});next();});
app.use('/api',(req,res,next)=>{const session=req.cookies.session?one('SELECT s.*,u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?',hash(req.cookies.session),Date.now()):null;res.locals.user=session;res.locals.csrf=session?.csrf;next();});
const auth=(req:any,res:any,next:any)=>{if(!res.locals.user)return res.status(401).json({error:'loginRequired'});if(!['GET','HEAD'].includes(req.method)&&req.get('x-csrf-token')!==res.locals.csrf)return res.status(403).json({error:'csrf'});next();};
const admin=(_req:any,res:any,next:any)=>res.locals.user?.role==='admin'?next():res.status(403).json({error:'adminRequired'});
const verified=(_user:any)=>{}; // Email verification is disabled by the owner's explicit request.
const owner=(p:any)=>{if(p.role!=='owner')throw new HttpError(403,'forbidden');};
const credentials=z.object({email:z.email().max(254).transform(emailKey),password:z.string().min(12).max(200)});
const sessions=(res:any,user:any)=>{const value=token(),csrf=token();run('INSERT INTO sessions VALUES(?,?,?,?)',hash(value),user.id,csrf,Date.now()+14*86400_000);res.cookie('session',value,{httpOnly:true,sameSite:'lax',secure:prod,path:process.env.APP_BASE||'/',maxAge:14*86400_000});return csrf;};
app.get('/api/health',(_req,res)=>res.json({ok:true,name:'Choirloom'}));
app.get('/api/voicebanks',(_req,res)=>res.json(voiceState(res.locals.user?.id)));
app.post('/api/voicebanks/import',auth,admin,(req,res)=>{const id=startVoiceImport(res.locals.user.id,req.body);res.status(202).json({id,...voiceState(res.locals.user.id)});});
app.post('/api/voicebanks/:id',auth,(req,res)=>res.json(startVoiceInstall(res.locals.user.id,String(req.params.id))));
app.delete('/api/voicebanks/:id',auth,admin,async(req,res)=>res.json(await removeVoice(res.locals.user.id,String(req.params.id))));
app.get('/api/session',(_req,res)=>res.json({user:res.locals.user?safeUser(res.locals.user):null,csrf:res.locals.csrf||'',capabilities:capabilities(),efforts}));
const authLimiter=rateLimit({keyGenerator:clientKey,windowMs:15*60000,limit:20,message:{error:'rateLimited'}});app.use('/api/auth',authLimiter);
app.post('/api/auth/signup',async(req,res)=>{const data=credentials.extend({name:z.string().trim().min(1).max(100),locale:z.enum(['en','zh-Hant']).default(preferredLocale(req.get('accept-language')))}).parse(req.body);if(one('SELECT id FROM users WHERE email=?',data.email)){res.json({message:'checkEmail'});return;}const password=await argon2.hash(data.password,{memoryCost:19456,timeCost:2,parallelism:1});const id=uid();try{run('INSERT INTO users(id,email,name,password,prefs,verified) VALUES(?,?,?,?,?,1)',id,data.email,data.name,password,JSON.stringify({locale:data.locale,effort:'medium'}));}catch{throw new HttpError(409,'accountExists');}const user=one('SELECT * FROM users WHERE id=?',id);res.status(201).json({user:safeUser(user),csrf:sessions(res,user),message:'checkEmail'});});
app.post('/api/auth/login',async(req,res)=>{const data=credentials.parse(req.body),user=one('SELECT * FROM users WHERE email=?',data.email);if(!user||!await argon2.verify(user.password,data.password))throw new HttpError(401,'badLogin');res.json({user:safeUser(user),csrf:sessions(res,user)});});
app.post('/api/auth/logout',auth,(req,res)=>{run('DELETE FROM sessions WHERE token=?',hash(req.cookies.session));res.clearCookie('session',{path:process.env.APP_BASE||'/'});res.json({ok:true});});
app.post('/api/auth/forgot',async(req,res)=>{const email=z.email().transform(emailKey).parse(req.body.email),user=one('SELECT * FROM users WHERE email=?',email);if(user)await sendToken(user,'reset');res.json({message:'checkEmail'});});
app.post('/api/auth/verify',async(req,res)=>{const value=z.string().min(20).max(100).parse(req.body.token);transaction(()=>{const row=one("SELECT * FROM tokens WHERE token=? AND kind='verify' AND expires>?",hash(value),Date.now());if(!row)throw new HttpError(400,'invalidToken');run('UPDATE users SET verified=1 WHERE id=?',row.user_id);run('DELETE FROM tokens WHERE token=?',hash(value));});res.json({ok:true});});
app.post('/api/auth/reset',async(req,res)=>{const value=z.string().min(20).max(100).parse(req.body.token);const password=z.string().min(12).max(200).parse(req.body.password);const ph=await argon2.hash(password,{memoryCost:19456,timeCost:2,parallelism:1});transaction(()=>{const row=one("SELECT * FROM tokens WHERE token=? AND kind='reset' AND expires>?",hash(value),Date.now());if(!row)throw new HttpError(400,'invalidToken');run('UPDATE users SET password=? WHERE id=?',ph,row.user_id);run('DELETE FROM tokens WHERE user_id=? AND kind=?',row.user_id,'reset');run('DELETE FROM sessions WHERE user_id=?',row.user_id);});res.json({ok:true});});
app.post('/api/auth/resend',auth,async(_req,res)=>{if(!res.locals.user.verified)await sendToken(res.locals.user,'verify');res.json({message:'checkEmail'});});
app.patch('/api/preferences',auth,(req,res)=>{const body=z.object({version:z.number().int(),patch:z.record(z.string(),z.unknown())}).parse(req.body);if(JSON.stringify(body.patch).length>32000)throw new HttpError(400,'invalidInput');const prefs={...JSON.parse(res.locals.user.prefs),...body.patch};delete prefs.__proto__;const r=run('UPDATE users SET prefs=?,pref_version=pref_version+1 WHERE id=? AND pref_version=?',JSON.stringify(prefs),res.locals.user.id,body.version);if(!r.changes)throw new HttpError(409,'conflict');res.json({prefs,version:body.version+1});});
app.get('/api/library',(_req,res)=>res.json(libraryCatalog()));
app.get('/api/library/:id',auth,async(req,res)=>res.json(await libraryScore(String(req.params.id),typeof req.query.part==='string'?req.query.part:undefined)));
app.post('/api/library/:id/import',auth,async(req,res)=>{const item=await libraryScore(String(req.params.id),z.string().max(100).optional().parse(req.body.part)),id=uid();transaction(()=>{run('INSERT INTO projects(id,owner,title,score,source) VALUES(?,?,?,?,?)',id,res.locals.user.id,item.score.title,JSON.stringify(item.score),JSON.stringify(item.source));run('INSERT INTO revisions(project_id,version,score,actor,label) VALUES(?,1,?,?,?)',id,JSON.stringify(item.score),res.locals.user.id,'library-import');});log('info','library.imported',{projectId:id,userId:res.locals.user.id,catalogId:req.params.id});res.json({id});});
app.get('/api/projects',auth,(_req,res)=>res.json(projectList(res.locals.user)));
app.post('/api/projects',auth,(req,res)=>{const score=req.body.demo?demoScore():newScore(res.locals.user.prefs&&JSON.parse(res.locals.user.prefs).locale==='en'?'Untitled melody':'未命名旋律');const pref=JSON.parse(res.locals.user.prefs||'{}');if(!req.body.demo&&Array.isArray(pref.ensemble)&&pref.ensemble.length){const draft=scoreSchema.safeParse({...score,parts:pref.ensemble.map((p:any)=>({...p,id:uid(),notes:[]})),styles:pref.styles||score.styles,textures:pref.textures||score.textures,tempo:pref.tempo||score.tempo,lyricsLanguage:pref.lyricsLanguage||score.lyricsLanguage});if(draft.success){Object.assign(score,draft.data);score.leadId=score.parts[0].id;}}const id=uid();transaction(()=>{run('INSERT INTO projects(id,owner,title,score) VALUES(?,?,?,?)',id,res.locals.user.id,score.title,JSON.stringify(score));run('INSERT INTO revisions(project_id,version,score,actor,label) VALUES(?,1,?,?,?)',id,JSON.stringify(score),res.locals.user.id,'created');});res.json({id});});
app.get('/api/projects/:id',auth,(req,res)=>res.json(projectDetails(String(req.params.id),res.locals.user)));
app.put('/api/projects/:id',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user,true);const score=scoreSchema.parse(req.body.score);const errors=validateScore(score).filter(f=>f.severity==='error');if(errors.length)throw new HttpError(422,errors[0].code);const version=revision(p,score,res.locals.user.id,'edit',z.number().int().parse(req.body.version));res.json({version,findings:validateScore(score)});});
app.put('/api/projects/:id/view',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user);if(JSON.stringify(req.body).length>32000)throw new HttpError(400,'invalidInput');const chat=currentChat(p.id,res.locals.user.id);if(req.body.chatId&&req.body.chatId!==chat.id)throw new HttpError(409,'conflict');run('INSERT INTO views VALUES(?,?,?) ON CONFLICT(project_id,user_id) DO UPDATE SET state=excluded.state',p.id,res.locals.user.id,JSON.stringify(req.body));run('UPDATE chat_sessions SET draft=? WHERE id=?',JSON.stringify({draft:req.body.draft||'',effort:req.body.effort||'medium',referenceIds:req.body.referenceIds||[],creationMode:req.body.creationMode||'arrange',barSelection:req.body.barSelection||null}),chat.id);res.json({ok:true});});
app.get('/api/projects/:id/revisions',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user);res.json(all('SELECT version,label,created FROM revisions WHERE project_id=? ORDER BY version DESC',p.id));});
app.post('/api/projects/:id/restore',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user,true);const row=one('SELECT score FROM revisions WHERE project_id=? AND version=?',p.id,z.number().int().parse(req.body.target));if(!row)throw new HttpError(404,'notFound');res.json({version:revision(p,JSON.parse(row.score),res.locals.user.id,'restored',req.body.version)});});
app.post('/api/projects/:id/chats',auth,(req,res)=>{res.json(switchChat(String(req.params.id),res.locals.user));});
app.post('/api/projects/:id/chats/:chatId/activate',auth,(req,res)=>{res.json(switchChat(String(req.params.id),res.locals.user,String(req.params.chatId)));});
app.post('/api/projects/:id/chats/rewind/:messageId',auth,(req,res)=>{const body=z.object({version:z.number().int().min(1),retry:z.boolean().default(false)}).parse(req.body);res.json(rewindChat(String(req.params.id),res.locals.user,String(req.params.messageId),body.version,body.retry));});
app.post('/api/projects/:id/ai',auth,(req,res)=>{const user=res.locals.user;verified(user);const p=access(String(req.params.id),user,true);const body=z.object({prompt:z.string().min(1).max(6000),effort:z.enum(efforts),locale:z.enum(['en','zh-Hant']),mode:z.enum(['chat','arrange','compose','revise']).default('chat'),referenceIds:z.array(z.string().max(100)).max(12).default([]),selection:z.object({startBar:z.number().int().min(1).max(1000),endBar:z.number().int().min(1).max(1000),partIds:z.array(z.string().max(100)).min(1).max(24).optional()}).optional(),conversationId:z.string().max(100).optional(),requestId:z.string().uuid().optional()}).parse(req.body);const chat=currentChat(p.id,user.id);if(body.conversationId&&body.conversationId!==chat.id)throw new HttpError(409,'conflict');body.conversationId=chat.id;if(body.selection){const score=JSON.parse(p.score);if(body.selection.startBar>body.selection.endBar||body.selection.endBar>Math.ceil(endTick(score)/barTicks(score))||body.selection.partIds?.some(id=>!score.parts.some((p:any)=>p.id===id)))throw new HttpError(400,'invalidBarSelection');}if(body.requestId){const old=one('SELECT j.id,j.status,j.kind,j.stage,j.progress FROM chats c JOIN jobs j ON j.id=c.job_id WHERE c.project_id=? AND c.user_id=? AND c.request_id=?',p.id,user.id,body.requestId);if(old){res.json(old);return;}}if(!connected())throw new HttpError(409,'connectAI');resolveReferences(p.id,user,body.referenceIds);const job=transaction(()=>{const j=createJob(p,user,'ai',body);run('INSERT INTO chats(id,project_id,user_id,role,content,job_id,reference_ids,request_id,conversation_id) VALUES(?,?,?,?,?,?,?,?,?)',uid(),p.id,user.id,'user',body.prompt,j.id,JSON.stringify(body.referenceIds),body.requestId||null,chat.id);run('UPDATE chat_sessions SET draft=?,title=CASE WHEN title LIKE ? THEN ? ELSE title END WHERE id=?',JSON.stringify({draft:'',effort:body.effort,referenceIds:[],creationMode:body.mode,barSelection:body.selection||null}),'Chat %',body.prompt.slice(0,60),chat.id);return j;});res.json(job);});
app.get('/api/projects/:id/revisions/:version',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user),r=one('SELECT version,score,label,created FROM revisions WHERE project_id=? AND version=?',p.id,z.coerce.number().int().positive().parse(req.params.version));if(!r)throw new HttpError(404,'notFound');res.json({...r,score:JSON.parse(r.score)});});

app.get('/api/ai/status',auth,(_req,res)=>res.json(loginStatus(res.locals.user)));
app.post('/api/ai/connect',auth,admin,(_req,res)=>res.json(startLogin(res.locals.user)));
app.post('/api/ai/disconnect',auth,admin,(_req,res)=>{writeFileSync(path.join(homes(),'.disabled'),'disabled');stopLogin(res.locals.user);for(const j of all("SELECT id FROM jobs WHERE kind='ai' AND status IN ('queued','running')"))cancelJob(j.id);rmSync(path.join(homes(),'auth.json'),{force:true});res.json(loginStatus(res.locals.user));});
app.post('/api/client-logs',rateLimit({keyGenerator:clientKey,windowMs:60000,limit:60,message:{error:'rateLimited'}}),(req,res)=>{if(JSON.stringify(req.body).length>60000)throw new HttpError(400,'invalidInput');const batch=telemetrySchema.parse(req.body);if(res.locals.user&&batch.csrf!==res.locals.csrf)throw new HttpError(403,'csrf');res.json(ingestClientLogs(res.locals.user,batch));});
app.get('/api/admin',auth,admin,(req,res)=>res.json(adminSnapshot(req.query)));
app.get('/api/admin/logs',auth,admin,(req,res)=>res.json(logs(req.query)));
app.patch('/api/admin/users/:id/role',auth,admin,(req,res)=>{const body=z.object({role:z.enum(['user','admin'])}).parse(req.body);setRole(res.locals.user,String(req.params.id),body.role);res.json({ok:true});});
app.post('/api/jobs/:id/retry',auth,(req,res)=>{const previous=one('SELECT * FROM jobs WHERE id=? AND user_id=?',String(req.params.id),res.locals.user.id);if(!previous)throw new HttpError(404,'notFound');if(!['failed','cancelled'].includes(previous.status))throw new HttpError(409,'jobBusy');const p=access(previous.project_id,res.locals.user,true);if(previous.kind==='ai'&&JSON.parse(previous.payload).conversationId&&JSON.parse(previous.payload).conversationId!==currentChat(p.id,res.locals.user.id).id)throw new HttpError(409,'conflict');if(previous.kind==='ai'&&!connected())throw new HttpError(409,'connectAI');res.json(createJob(p,res.locals.user,previous.kind,{...JSON.parse(previous.payload),retryOf:previous.id}));});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:1}});
app.post('/api/projects/:id/references',auth,upload.single('file'),async(req,res)=>{if(!req.file)throw new HttpError(400,'invalidInput');res.json(await addReference(String(req.params.id),res.locals.user,req.file));});
app.get('/api/references/:id',auth,(req,res)=>{const file=referenceFile(String(req.params.id),res.locals.user);res.download(file.path,file.name);});
app.patch('/api/references/:id',auth,(req,res)=>{const file=referenceFile(String(req.params.id),res.locals.user);access(file.project_id,res.locals.user,true);if(file.user_id!==res.locals.user.id)throw new HttpError(403,'forbidden');run('UPDATE references_files SET archived=? WHERE id=?',Number(z.boolean().parse(req.body.archived)),file.id);res.json({ok:true});});
app.post('/api/projects/:id/import',auth,upload.single('file'),async(req,res)=>{const p=access(String(req.params.id),res.locals.user,true);if(!req.file)throw new HttpError(400,'invalidImport');const ext=path.extname(req.file.originalname).toLowerCase();let score:Score;
 if(['.xml','.musicxml','.mxl'].includes(ext))score=fromMusicXML(ext==='.mxl'?readMXL(req.file.buffer):req.file.buffer.toString());else if(['.mid','.midi'].includes(ext)){const midi=new Midi(req.file.buffer);score=newScore(midi.name||'Imported MIDI');score.tempo=midi.header.tempos[0]?.bpm||88;score.parts=midi.tracks.filter(t=>t.notes.length).map(t=>{const part=createPart();part.name=t.name||'Voice';part.notes=t.notes.map(n=>({id:uid(),pitch:n.midi,start:Math.round(n.ticks/midi.header.ppq*PPQ),duration:Math.max(1,Math.round(n.durationTicks/midi.header.ppq*PPQ)),lyric:'',syllabic:'single',tie:'none',locked:false}));return part;});score.leadId=score.parts[0]?.id||'';score=scoreSchema.parse(score);}else if(['.pdf','.png','.jpg','.jpeg','.tif','.tiff','.svg'].includes(ext)){verified(res.locals.user);if(!capabilities().scoreRecognition)throw new HttpError(409,'connectAI');const dir=path.join(dataDir,'uploads',p.id);mkdirSync(dir,{recursive:true,mode:0o700});const file=path.join(dir,uid()+(ext==='.svg'?'.png':ext));let input=req.file.buffer;if(ext==='.svg'){try{input=await rasterizeScoreSvg(input);}catch(error:any){throw new HttpError(422,['invalidSvg','svgExternalResource'].includes(error.message)?error.message:'invalidSvg');}}writeFileSync(file,input);res.json({job:createJob(p,res.locals.user,'import',{file})});return;}else throw new HttpError(400,'invalidImport');const findings=validateScore(score);if(findings.some(f=>f.severity==='error'))throw new HttpError(422,'invalidImport');const version=revision(p,score,res.locals.user.id,'import',p.version);res.json({score,version,findings});});
app.post('/api/projects/:id/render',auth,(req,res)=>{verified(res.locals.user);const p=access(String(req.params.id),res.locals.user,true);if(!capabilities().diffsinger)throw new HttpError(503,'singerUnavailable');requireVoices(res.locals.user.id,JSON.parse(p.score));res.json(createJob(p,res.locals.user,'render',{}));});
app.get('/api/jobs/:id',auth,(req,res)=>{const j=one('SELECT * FROM jobs WHERE id=? AND (user_id=? OR ?=1)',String(req.params.id),res.locals.user.id,res.locals.user.role==='admin'?1:0);if(!j)throw new HttpError(404,'notFound');access(j.project_id,res.locals.user);res.json({...j,payload:undefined,result:j.result?JSON.parse(j.result):null});});
app.delete('/api/jobs/:id',auth,(req,res)=>{const j=one('SELECT * FROM jobs WHERE id=? AND user_id=?',String(req.params.id),res.locals.user.id);if(!j)throw new HttpError(404,'notFound');access(j.project_id,res.locals.user,true);cancelJob(j.id);res.json({ok:true});});

app.get('/api/projects/:id/sharing',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user);owner(p);res.json({members:all('SELECT email,role FROM members WHERE project_id=?',p.id),links:all('SELECT id,version,downloads,expires FROM shares WHERE project_id=?',p.id)});});
app.post('/api/projects/:id/members',auth,async(req,res)=>{const p=access(String(req.params.id),res.locals.user);owner(p);verified(res.locals.user);const body=z.object({email:z.email().transform(emailKey),role:z.enum(['viewer','editor'])}).parse(req.body);run('INSERT INTO members VALUES(?,?,?) ON CONFLICT(project_id,email) DO UPDATE SET role=excluded.role',p.id,body.email,body.role);if(process.env.SMTP_HOST)await sendMail(body.email,'Choirloom · 專案邀請 / Project invitation',`有人與您分享合唱專案 / A vocal arrangement has been shared with you.\n${origin}${process.env.APP_BASE||''}/?project=${p.id}\n請使用此電子郵件註冊並驗證。Sign in with this verified email address.`);res.json({ok:true});});
app.delete('/api/projects/:id/members',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user);owner(p);run('DELETE FROM members WHERE project_id=? AND email=?',p.id,emailKey(req.body.email));res.json({ok:true});});
app.post('/api/projects/:id/shares',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user);owner(p);verified(res.locals.user);const body=z.object({downloads:z.boolean().default(false),days:z.number().int().min(1).max(365).default(30)}).parse(req.body);const value=token(),id=uid();run('INSERT INTO shares(id,project_id,token,version,downloads,expires) VALUES(?,?,?,?,?,?)',id,p.id,hash(value),p.version,Number(body.downloads),Date.now()+body.days*86400_000);res.json({id,url:`${origin}${process.env.APP_BASE||''}/?share=${value}`});});
app.delete('/api/projects/:id/shares/:share',auth,(req,res)=>{const p=access(String(req.params.id),res.locals.user);owner(p);run('DELETE FROM shares WHERE id=? AND project_id=?',String(req.params.share),p.id);res.json({ok:true});});
function shared(value:any){if(typeof value!=='string')throw new HttpError(404,'notFound');const link=one('SELECT * FROM shares WHERE token=? AND expires>?',hash(value),Date.now());if(!link)throw new HttpError(404,'notFound');return link;}
app.get('/api/shared/:token',(req,res)=>{const link=shared(req.params.token),r=one('SELECT score FROM revisions WHERE project_id=? AND version=?',link.project_id,link.version);const render=one("SELECT result FROM jobs WHERE project_id=? AND kind='render' AND status='complete' AND json_extract(result,'$.version')=? ORDER BY created DESC LIMIT 1",link.project_id,link.version);res.json({score:JSON.parse(r.score),version:link.version,downloads:!!link.downloads,id:link.project_id,role:'viewer',chats:[],view:{},render:render?JSON.parse(render.result):null});});
app.get('/api/projects/:id/export/:format',async(req,res)=>{
 let p:any,pinnedVersion:number|undefined;
 if(req.query.share){const link=shared(req.query.share);if(link.project_id!==req.params.id||!link.downloads)throw new HttpError(403,'forbidden');p={id:link.project_id,version:link.version,score:one('SELECT score FROM revisions WHERE project_id=? AND version=?',link.project_id,link.version).score};pinnedVersion=link.version;}
 else{if(!res.locals.user)throw new HttpError(401,'loginRequired');p=access(String(req.params.id),res.locals.user);if(req.query.version){const version=z.coerce.number().int().positive().parse(req.query.version),saved=one('SELECT score FROM revisions WHERE project_id=? AND version=?',p.id,version);if(!saved)throw new HttpError(404,'notFound');p={...p,score:saved.score,version};}}
 const score=JSON.parse(p.score) as Score,chosen=selection(score,req.query),format=String(req.params.format),separate=req.query.separate==='1';
 if(['wav','mp3'].includes(format)){
  const abort=new AbortController(),stop=()=>abort.abort();res.once('close',stop);const timeout=setTimeout(stop,120000);
  try{const output=await audioExport(p.id,score,chosen,format,separate,abort.signal,pinnedVersion);res.download(output.file,output.name,error=>{output.cleanup();if(error&&!res.headersSent&&!res.destroyed)res.status(500).end();});}
  finally{clearTimeout(timeout);res.off('close',stop);}return;
 }
 const output=structuredExport(chosen,format,separate);res.attachment(output.name).type(output.mime).send(Buffer.from(output.bytes));
});
app.get('/api/artifacts/:id',(req,res)=>{const a=one('SELECT * FROM artifacts WHERE id=?',String(req.params.id));if(!a)throw new HttpError(404,'notFound');if(req.query.share){const link=shared(req.query.share);if(link.project_id!==a.project_id||link.version!==a.version)throw new HttpError(403,'forbidden');}else{if(!res.locals.user)throw new HttpError(401,'loginRequired');access(a.project_id,res.locals.user);}res.type(a.mime).sendFile(a.path);});
app.use('/api',(_req,res)=>res.status(404).json({error:'notFound'}));app.use('/assets',express.static(path.resolve('assets'),{dotfiles:'deny',maxAge:'1d'}));app.use(express.static(path.resolve('dist')));app.get('/{*path}',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));
app.use((error:any,_req:any,res:any,_next:any)=>{log('error','http.failed',{requestId:res.locals.requestId,userId:res.locals.user?.id,path:_req.path,error});const code=error instanceof HttpError?error.message:error instanceof z.ZodError?'invalidInput':['invalidImport','polyphonicImport','emptyScore'].includes(error.message)?error.message:'serverError';res.status(error instanceof HttpError?error.status:error instanceof z.ZodError?400:500).json({error:code});});
export function createHttpServer(){const server=createServer(app);attachRealtime(server);return server;}
if(process.env.NODE_ENV!=='test'){
 process.on('unhandledRejection',error=>log('error','process.unhandledRejection',{error}));process.on('uncaughtExceptionMonitor',error=>log('error','process.uncaughtException',{error}));
 recoverVoiceInstalls();recoverVoiceImports();startWorker();const server=createHttpServer(),port=process.env.PORT||'8787';const ready=()=>log('info','server.ready',{pid:process.pid,node:process.version,transport:/^\\\\/.test(port)?'IIS named pipe':'HTTP',realtime:'websocket'});
 if(/^\\\\/.test(port))server.listen(port,ready);else server.listen(Number(port),process.env.HOST||'127.0.0.1',ready);
}
