import {recognizeScore} from './score-recognition.ts';
import {expandRepeats} from '../shared/repeats.ts';
import {spawn} from 'node:child_process';
import {existsSync,mkdirSync,readFileSync,readdirSync,writeFileSync,renameSync} from 'node:fs';
import path from 'node:path';
import {db,all,one,run,revision,access,dataDir,HttpError} from './db.ts';
import {arrange,connected} from './ai.ts';
import {uid,singingKey,fromMusicXML,readMXL,scoreSchema,type Score} from '../shared/music.ts';
import {publicBanks,catalogPath,voiceCache,requireVoices} from './voicebanks.ts';
import {events} from './events.ts';
import {log} from './diagnostics.ts';
const active=new Map<string,AbortController>();
export function createJob(p:any,user:any,kind:string,payload:any){if(one("SELECT id FROM jobs WHERE user_id=? AND status IN ('queued','running')",user.id))throw new HttpError(429,'jobBusy');const id=uid();run('INSERT INTO jobs(id,project_id,user_id,kind,status,payload) VALUES(?,?,?,?,?,?)',id,p.id,user.id,kind,'queued',JSON.stringify({...payload,version:p.version}));log('info','job.queued',{jobId:id,projectId:p.id,userId:user.id,kind});return {id,status:'queued',kind,stage:'queued',progress:0};}
export function cancelJob(id:string){active.get(id)?.abort();run("UPDATE jobs SET status='cancelled',stage='cancelled',updated=CURRENT_TIMESTAMP WHERE id=? AND status IN ('queued','running')",id);log('info','job.cancelled',{jobId:id});}
export function capabilities(){return {scoreRecognition:connected(),nnsvs:!!process.env.NNSVS_COMMAND&&existsSync(process.env.NNSVS_COMMAND),mail:!!process.env.SMTP_HOST,voicebanks:readVoicebanks()};}
export function readVoicebanks():any[]{return publicBanks().filter(b=>b.installable);}
export function processCommand(command:string,args:string[],signal:AbortSignal,cwd?:string,context:Record<string,any>={}):Promise<string>{return new Promise((resolve,reject)=>{if(signal.aborted){reject(Error('cancelled'));return;}const child=spawn(command,args,{cwd,env:{...process.env,CHOIRLOOM_PARENT_PID:String(process.pid)},windowsHide:true,stdio:['ignore','pipe','pipe']});let out='',progressBuffer='';const completedNotes=new Set<string>();log('info','worker.started',{...context,executable:path.basename(command),pid:child.pid});const abort=()=>{if(process.platform==='win32'&&child.pid){spawn(path.join(process.env.SystemRoot||'C:\\Windows','System32','taskkill.exe'),['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'}).once('error',()=>child.kill());}else child.kill();};signal.addEventListener('abort',abort,{once:true});const output=(d:Buffer,stream:string)=>{const text=d.toString();out=(out+text).slice(-20000);log('debug','worker.output',{...context,stream},text);if(stream==='stdout'&&context.renderTotal){progressBuffer+=text;const lines=progressBuffer.split(/\r?\n/);progressBuffer=lines.pop()!.slice(-20000);for(const line of lines){let update:any;try{update=JSON.parse(line);}catch{continue;}if(typeof update.note!=='string')continue;completedNotes.add(String(update.part)+':'+update.note);const count=completedNotes.size,progress=Math.min(95,10+Math.floor(count/context.renderTotal*85));run("UPDATE jobs SET progress=?,stage=?,updated=CURRENT_TIMESTAMP WHERE id=? AND status='running'",progress,`rendering:${count}:${context.renderTotal}`,context.jobId);}}};child.stdout.on('data',d=>output(d,'stdout'));child.stderr.on('data',d=>output(d,'stderr'));child.on('error',e=>{log('error','worker.spawn.failed',{...context,error:e});signal.removeEventListener('abort',abort);reject(e);});child.on('close',code=>{log(code===0?'info':'error','worker.exited',{...context,exitCode:code},code===0?'':out);signal.removeEventListener('abort',abort);if(code===0)resolve(out);else reject(out.includes('unknownPronunciation:')||out.includes('unsupportedPhoneme:')?new HttpError(422,'pronunciationUnsupported'):Error('workerFailed'));});});}
function artifact(job:any,file:string,mime:string,name:string){const id=uid();run('INSERT INTO artifacts(id,project_id,version,path,mime,name) VALUES(?,?,?,?,?,?)',id,job.project_id,JSON.parse(job.payload).version,file,mime,name);return {id,mime,name};}
export function recoverJobs(){for(const row of all("SELECT id,worker_pid FROM jobs WHERE status='running'")){if(active.has(row.id))continue;let alive=false;if(row.worker_pid)try{process.kill(row.worker_pid,0);alive=true;}catch{}if(alive)continue;run("UPDATE jobs SET status='queued',stage='queued',error=NULL,worker_pid=NULL,updated=CURRENT_TIMESTAMP WHERE id=? AND status='running' AND worker_pid IS ?",row.id,row.worker_pid);}}
function checkpoint<T>(dir:string,name:string,produce:()=>Promise<T>):Promise<T>{const file=path.join(dir,name+'.json');if(existsSync(file))return Promise.resolve(JSON.parse(readFileSync(file,'utf8')));return produce().then(value=>{writeFileSync(file+'.tmp',JSON.stringify(value));renameSync(file+'.tmp',file);return value;});}
export async function tick(){if(active.size)return;recoverJobs();const job=one("SELECT * FROM jobs WHERE status='queued' AND (kind='ai' OR NOT EXISTS(SELECT 1 FROM voice_imports WHERE status='running')) ORDER BY created LIMIT 1");if(!job)return;const abort=new AbortController();if(!run("UPDATE jobs SET status='running',stage='starting',worker_pid=?,updated=CURRENT_TIMESTAMP WHERE id=? AND status='queued'",process.pid,job.id).changes)return;active.set(job.id,abort);const context={jobId:job.id,projectId:job.project_id,userId:job.user_id,kind:job.kind};log('info','job.started',context);let timedOut=false;const renderNotes=job.kind==='render'?JSON.parse(one('SELECT score FROM projects WHERE id=?',job.project_id).score).parts.flatMap((p:any)=>p.notes).filter((n:any)=>n.pitch!==null&&!['stop','continue'].includes(n.tie)).length:0;const budget=job.kind==='render'?Math.min(2*60*60_000,Math.max(20*60_000,5*60_000+renderNotes*60_000)):20*60_000;const timeout=setTimeout(()=>{timedOut=true;abort.abort();},budget);try{const user=one('SELECT * FROM users WHERE id=?',job.user_id);const p=access(job.project_id,user,true),payload={...JSON.parse(job.payload),jobId:job.id};if(p.version!==payload.version)throw new HttpError(409,'conflict');const dir=path.join(dataDir,'jobs',job.id);mkdirSync(dir,{recursive:true,mode:0o700});let result:any;
 if(job.kind==='ai'){const generated=await checkpoint(dir,'arrangement',()=>arrange(user,p,payload,abort.signal,(n,stage='receiving-ai')=>{run('UPDATE jobs SET progress=?,stage=?,updated=CURRENT_TIMESTAMP WHERE id=? AND (progress<>? OR stage<>?)',n,stage,job.id,n,stage);}));access(job.project_id,user,true);if(abort.signal.aborted)throw Error('cancelled');db.exec('BEGIN IMMEDIATE');let version=p.version;if(generated.score)version=revision(p,generated.score,user.id,'ai',payload.version);run('INSERT INTO chats(id,project_id,user_id,role,content,job_id,revision,reference_ids,conversation_id) VALUES(?,?,?,?,?,?,?,?,?)',uid(),p.id,user.id,'assistant',generated.message,job.id,version,JSON.stringify(payload.referenceIds||[]),payload.conversationId||'');result={version,message:generated.message};}
 else if(job.kind==='import'){const recognized=await checkpoint(dir,'recognition',()=>recognizeScore(payload.file,dir,abort.signal,(progress,stage)=>{run("UPDATE jobs SET progress=?,stage=?,updated=CURRENT_TIMESTAMP WHERE id=? AND status='running'",progress,stage,job.id);}));const {output,...review}=recognized;access(job.project_id,user,true);abort.signal.throwIfAborted();db.exec('BEGIN IMMEDIATE');const version=revision(p,review.score,user.id,'import',payload.version);result={...review,version,files:[artifact(job,output,'application/vnd.recordare.musicxml+xml','recognized.musicxml')]};}
 else if(job.kind==='render'){if(!capabilities().nnsvs)throw Error('singerUnavailable');const input=path.join(dir,'score.json');const performanceScore=expandRepeats(JSON.parse(p.score));writeFileSync(input,JSON.stringify(performanceScore));run("UPDATE jobs SET stage='rendering' WHERE id=?",job.id);requireVoices(user.id,JSON.parse(p.score));run("UPDATE jobs SET stage='validating-lyrics' WHERE id=?",job.id);await processCommand(process.env.NNSVS_COMMAND!,['--score',input,'--output',path.join(dir,'pronunciation-check'),'--voicebanks',catalogPath,'--cache',voiceCache(user.id),'--validate-lyrics','true'],abort.signal,undefined,context);run("UPDATE jobs SET stage='rendering' WHERE id=?",job.id);await processCommand(process.env.NNSVS_COMMAND!,['--score',input,'--output',dir,'--voicebanks',catalogPath,'--cache',voiceCache(user.id)],abort.signal,undefined,{...context,renderTotal:performanceScore.parts.flatMap((p:any)=>p.notes).filter((n:any)=>n.pitch!==null&&!['stop','continue'].includes(n.tie)).length});db.exec('BEGIN IMMEDIATE');result={version:p.version,key:singingKey(JSON.parse(p.score)),files:readdirSync(dir).filter(f=>/\.(wav|mp3)$/.test(f)).map(f=>artifact(job,path.join(dir,f),f.endsWith('.mp3')?'audio/mpeg':'audio/wav',f))};if(!result.files.length)throw Error('workerFailed');}
 else throw Error('unknownJob');access(job.project_id,user,true);if(abort.signal.aborted)throw Error('cancelled');if(!run("UPDATE jobs SET status='complete',stage='complete',progress=100,result=?,updated=CURRENT_TIMESTAMP WHERE id=? AND status='running'",JSON.stringify(result),job.id).changes)throw Error('cancelled');if(db.isTransaction)db.exec('COMMIT');log('info','job.completed',context);
 }catch(error){if(db.isTransaction)db.exec('ROLLBACK');log('error','job.failed',{...context,error,aborted:abort.signal.aborted});run("UPDATE jobs SET status=?,stage=?,error=?,updated=CURRENT_TIMESTAMP WHERE id=? AND status='running'",abort.signal.aborted&&!timedOut?'cancelled':'failed',abort.signal.aborted&&!timedOut?'cancelled':'failed',timedOut?'workerTimedOut':error instanceof HttpError?error.message:['connectAI','singerUnavailable','invalidImport','workerFailed','aiFailed'].includes((error as Error).message)?(error as Error).message:'jobFailed',job.id);}finally{clearTimeout(timeout);active.delete(job.id);kick();}}
let enabled=false,scheduled=false;
function kick(){if(!enabled||scheduled||active.size)return;scheduled=true;setImmediate(()=>{scheduled=false;void tick().catch(error=>log('error','worker.queue.failed',{error}));});}
export function workerStatus(){return {enabled,active:[...active.keys()],queued:one("SELECT COUNT(*) AS count FROM jobs WHERE status='queued'").count};}
export function startWorker(){if(enabled)return;enabled=true;recoverJobs();setInterval(()=>{recoverJobs();kick();},10000).unref();events.on('change',table=>{if(table==='jobs'||table==='voice_imports')kick();});kick();log('info','worker.ready',workerStatus());}

