import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import path from 'node:path';import {createHash} from 'node:crypto';import {XMLParser} from 'fast-xml-parser';
import {dataDir,HttpError} from './db.ts';import {readMXL,fromMusicXML,validateScore,type Finding} from '../shared/music.ts';import {log} from './diagnostics.ts';
let cached:any;
function manifest(){return cached??=JSON.parse(readFileSync(process.env.SCORE_LIBRARY_MANIFEST||path.resolve('config/score-library.json'),'utf8'));}
export function libraryCatalog(){const m=manifest();return {sourceUrl:m.sourceUrl,licenseUrl:m.licenseUrl,commit:m.commit,songs:m.songs.map(({url,blobSha,...s}:any)=>s)};}
const list=(v:any):any[]=>v===undefined?[]:Array.isArray(v)?v:[v];
export function vocalParts(xml:string){if(xml.length>8_000_000||/<!ENTITY|<!DOCTYPE[^>]*\[/i.test(xml))throw new HttpError(422,'invalidImport');const root=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false}).parse(xml)['score-partwise'];if(!root)throw new HttpError(422,'invalidImport');const names=new Map(list(root['part-list']?.['score-part']).map(p=>[p['@_id'],p['part-name']]));const parts=list(root.part).map(p=>{const notes=list(p.measure).flatMap(m=>list(m.note)),lyrics=notes.filter(n=>n.lyric).length;return {id:p['@_id'],name:String(names.get(p['@_id'])||'Voice'),lyrics,notes:notes.length};}).filter(p=>p.notes>0);const vocal=parts.filter(p=>p.lyrics>0);return vocal.length?vocal:parts;}
export async function libraryScore(id:string,partId?:string){
 const entry=manifest().songs.find((s:any)=>s.id===id);if(!entry)throw new HttpError(404,'notFound');const url=new URL(entry.url);if(url.hostname!=='raw.githubusercontent.com'||!url.pathname.startsWith('/OpenScore/Lieder/')||!url.pathname.endsWith('.mxl')||url.protocol!=='https:')throw new HttpError(500,'invalidCatalog');
 const dir=path.join(dataDir,'score-library');mkdirSync(dir,{recursive:true});const file=path.join(dir,entry.blobSha+'.mxl');let bytes:Buffer;
 if(existsSync(file))bytes=readFileSync(file);else{const response=await fetch(url,{signal:AbortSignal.timeout(30000),redirect:'error'});if(!response.ok)throw new HttpError(502,'scoreSourceUnavailable');if(Number(response.headers.get('content-length'))>8_000_000)throw new HttpError(413,'invalidImport');const reader=response.body!.getReader(),chunks:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>8_000_000){await reader.cancel();throw new HttpError(413,'invalidImport');}chunks.push(value);}bytes=Buffer.concat(chunks);}
 const sha=createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');if(sha!==entry.blobSha)throw new HttpError(502,'scoreSourceChanged');if(!existsSync(file))writeFileSync(file,bytes);
 const xml=readMXL(bytes),parts=vocalParts(xml),chosen=partId?parts.find(p=>p.id===partId):parts[0];if(!chosen)throw new HttpError(422,'noVocalPart');const adjustments:Finding[]=[];const score=fromMusicXML(xml,[chosen.id],adjustments);score.title=entry.title;score.composer=entry.composer;score.lyricsLanguage=entry.languages[0]||'en';const findings=[...adjustments,...validateScore(score)];if(findings.some(f=>f.severity==='error')){log('warn','library.score.validation.failed',{catalogId:id,partId:chosen.id,findings:findings.filter(f=>f.severity==='error')});throw new HttpError(422,'scoreNeedsExternalEdit');}log('info','library.score.loaded',{catalogId:id,partId:chosen.id,notes:chosen.notes});return {score,parts,selectedPart:chosen.id,source:{id:entry.id,name:entry.source,url:entry.sourceUrl,license:entry.license,lyricist:entry.lyricist},findings};
}
