import {spawn} from 'node:child_process';
import {existsSync,mkdirSync,readFileSync,writeFileSync,readdirSync,statSync,rmSync,renameSync} from 'node:fs';
import {cp,rm,statfs} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {all,one,run,transaction,HttpError} from './db.ts';
import {changed} from './events.ts';
import {log} from './diagnostics.ts';
import {catalog,voiceCache,workerAlive} from './voicebanks.ts';
import {downloadVoice} from './voice-download.ts';
import {chooseConfiguration,sourceUrl,verifyWave} from '../shared/voice-import.ts';
import {demoScore} from '../shared/music.ts';

export const importSchema=z.object({name:z.string().trim().min(1).max(120),url:z.string().url().max(2048),licenseUrl:z.string().url().max(2048),publisher:z.string().trim().min(1).max(120),configuration:z.string().max(400).optional(),vocoderUrl:z.string().url().max(2048).optional()});
const root=path.resolve(process.env.VOICE_IMPORT_TEMP||path.join(os.tmpdir(),'choirloom-imports'));let busy=false;
const folder=(id:string)=>{if(!/^[a-f0-9-]{36}$/.test(id))throw Error('invalidImportId');return path.join(root,id);};
function stage(id:string,value:string,progress=0,report?:any){run('UPDATE voice_imports SET stage=?,progress=?,report=COALESCE(?,report),updated=CURRENT_TIMESTAMP WHERE id=?',value,progress,report?JSON.stringify(report):null,id);log('info','voice.import.stage',{importId:id,stage:value,progress});}
function native(args:string[],id:string,timeout=300000):Promise<string>{return new Promise((resolve,reject)=>{const child=spawn(process.env.DIFFSINGER_COMMAND!,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});let output='',errors='';const timer=setTimeout(()=>child.kill(),timeout);child.stdout.on('data',chunk=>{output=(output+chunk).slice(-2_000_000);});child.stderr.on('data',chunk=>{errors=(errors+chunk).slice(-6000);log('debug','voice.import.worker',{importId:id},chunk.toString());});child.on('error',e=>{clearTimeout(timer);reject(e);});child.on('close',code=>{clearTimeout(timer);code===0?resolve(output):reject(Error(errors||'nativeVerificationFailed:'+code));});});}
function size(file:string):number{const s=statSync(file);return s.isDirectory()?readdirSync(file).reduce((n,f)=>n+size(path.join(file,f)),0):s.size;}
async function processImport(row:any){run("UPDATE voice_imports SET status='running',worker_pid=?,error=NULL WHERE id=?",process.pid,row.id);const work=folder(row.id),cache=path.join(work,'cache');mkdirSync(cache,{recursive:true});const request=JSON.parse(row.request);let candidate:any;const created:string[]=[];let installed=false;
 try{
  stage(row.id,'downloading');const archive=path.join(cache,'package.zip'),asset=await downloadVoice(request.url,archive,(bytes,total)=>stage(row.id,'downloading',total?Math.round(bytes/total*90):0));renameSync(archive,path.join(cache,asset.sha256));
  const existing=catalog().find(b=>b.bundle?.sha256===asset.sha256&&(!request.configuration||b.dsConfig===request.configuration));if(existing?.availabilityReason==='publisherPermissionRequired')throw Error('publisherPermissionRequired: '+existing.licenseUrl);if(existing&&one("SELECT bank_id FROM voice_library WHERE bank_id=? AND status='installed'",existing.id))throw Error('voiceAlreadyInstalled: '+existing.name);
  stage(row.id,'inspecting');const report=JSON.parse((await native(['--inspect-bank',path.join(cache,asset.sha256)],row.id)).trim());stage(row.id,'inspected',100,report);
  const config=chooseConfiguration(report.choices,request.configuration);candidate={id:'import-'+row.id,name:request.name,version:'Imported '+new Date().toISOString().slice(0,10),source:request.publisher,sourceUrl:sourceUrl(request.url).href,licenseUrl:sourceUrl(request.licenseUrl).href,attribution:'AI synthesized · '+request.publisher,installable:true,imported:true,bundle:asset,dsConfig:config.dsConfig,...(config.innerArchive?{innerArchive:config.innerArchive}:{}),dictionary:catalog().find(b=>b.dictionary)?.dictionary,languageCodes:[],supportedLanguages:['Wordless / 無詞'],description:{en:'Verified wordless singing with the original publisher model and default speaker. Publisher terms apply.','zh-Hant':'已驗證原始聲庫的預設音色及無詞演唱。須遵守發布者條款。'}};
  if(existing)candidate.id=existing.id;
  if(!config.embeddedVocoder){const vocoders=JSON.parse(readFileSync(path.resolve('config/voice-vocoders.json'),'utf8'));if(request.vocoderUrl){candidate.vocoderBundle=await downloadVoice(request.vocoderUrl,path.join(cache,'vocoder.zip'));renameSync(path.join(cache,'vocoder.zip'),path.join(cache,candidate.vocoderBundle.sha256));}else {const vocoder=vocoders[config.vocoder];if(!vocoder)throw Error('unknownVocoder: '+config.vocoder+' — provide the publisher’s ONNX vocoder ZIP URL');Object.assign(candidate,vocoder);}}
  for(const entry of [candidate.vocoderBundle,candidate.dictionary].filter(Boolean)){const target=path.join(cache,entry.sha256);if(!existsSync(target)){const shared=path.join(voiceCache(),entry.sha256);if(existsSync(shared))await cp(shared,target);else await downloadVoice(entry.url,target,()=>{},entry.sha256);}}
  const manifest=path.join(work,'voicebanks.json');writeFileSync(manifest,JSON.stringify([candidate]));stage(row.id,'validating');await native(['--install',candidate.id,'--voicebanks',manifest,'--cache',cache],row.id);
  // Test all wordless syllables plus a representative lyric for each advertised language.
  const lyrics=['ah','woo','ba','bom','da','dum','doo','dap','bwee'];if(config.languageCodes.includes('en'))lyrics.push('hello');if(config.languageCodes.includes('zh'))lyrics.push('啊');if(config.languageCodes.includes('ja'))lyrics.push('あ');
  const score=demoScore();score.parts=score.parts.slice(0,1);score.parts[0].voicebank=candidate.id;const note=score.parts[0].notes.find(n=>n.pitch!==null)!;score.parts[0].notes=lyrics.map((lyric,i)=>({...note,id:randomUUID(),start:i*240,duration:240,lyric,syllabic:'single' as const,tie:'none' as const}));const scorePath=path.join(work,'score.json'),audio=path.join(work,'audio');writeFileSync(scorePath,JSON.stringify(score));stage(row.id,'rendering');await native(['--voicebanks',manifest,'--cache',cache,'--score',scorePath,'--output',audio],row.id,15*60_000);
  const verification={...verifyWave(readFileSync(path.join(audio,'mix.wav')),statSync(path.join(audio,'mix.mp3')).size),lyrics,checkedAt:new Date().toISOString(),sha256:asset.sha256};candidate.languageCodes=config.languageCodes;candidate.supportedLanguages=[...config.languageCodes.map((l:string)=>({en:'English',zh:'Chinese',ja:'Japanese'}[l]||l)),'Wordless / 無詞'];candidate.checkedAt=verification.checkedAt;candidate.description={en:'Verified '+candidate.supportedLanguages.join(', ')+' using the original model and default speaker. Publisher terms apply.','zh-Hant':'已驗證 '+candidate.supportedLanguages.join('、')+'；使用原始聲庫及預設音色。須遵守發布者條款。'};
  stage(row.id,'installing',0,{...report,verification});const shared=voiceCache();mkdirSync(shared,{recursive:true});let bytes=0;
  for(const entry of [candidate.bundle,candidate.vocoderBundle,candidate.dictionary].filter(Boolean))for(const suffix of ['',...(entry.archive?['.files']:[])]){const source=path.join(cache,entry.sha256+suffix),destination=path.join(shared,entry.sha256+suffix);if(!existsSync(destination)){const space=await statfs(shared);if(Number(space.bavail)*Number(space.bsize)<size(source)+1024**3)throw Error('insufficientVoiceStorage');const pending=destination+'.import-'+row.id;created.push(pending);writeFileSync(path.join(work,'cleanup.json'),JSON.stringify(created));await cp(source,pending,{recursive:true});if(size(source)!==size(pending))throw Error('installationCopyIncomplete');renameSync(pending,destination);created.push(destination);writeFileSync(path.join(work,'cleanup.json'),JSON.stringify(created));}bytes+=size(destination);}
  transaction(()=>{run('INSERT INTO voice_custom(bank_id,manifest) VALUES(?,?) ON CONFLICT(bank_id) DO UPDATE SET manifest=excluded.manifest',candidate.id,JSON.stringify(candidate));run("INSERT INTO voice_library(bank_id,status,progress,bytes) VALUES(?,'installed',100,?) ON CONFLICT(bank_id) DO UPDATE SET status='installed',progress=100,bytes=excluded.bytes,error=NULL",candidate.id,bytes);run('UPDATE voice_imports SET bank_id=? WHERE id=?',candidate.id,row.id);});installed=true;await rm(work,{recursive:true,force:true});run("UPDATE voice_imports SET status='completed',stage='completed',progress=100,bank_id=?,error=NULL,updated=CURRENT_TIMESTAMP WHERE id=?",candidate.id,row.id);changed('catalog');
 }catch(error:any){log('error','voice.import.failed',{importId:row.id,error});run("UPDATE voice_imports SET status='failed',stage='failed',error=?,updated=CURRENT_TIMESTAMP WHERE id=?",String(error.message).slice(-3000),row.id);
 }finally{try{if(!installed)for(const file of created){if(!path.resolve(file).startsWith(path.resolve(voiceCache())+path.sep))throw Error('unsafeCleanupPath');await rm(file,{recursive:true,force:true});}await rm(work,{recursive:true,force:true});log('info','voice.import.cleaned',{importId:row.id});}catch(error){log('error','voice.import.cleanup.failed',{importId:row.id,error});run("UPDATE voice_imports SET status='running',stage='cleanup-failed',error='Temporary cleanup failed; new imports are paused.',updated=CURRENT_TIMESTAMP WHERE id=?",row.id);throw error;}}
}
export function startVoiceImport(userId:string,input:unknown){const request=importSchema.parse(input);try{sourceUrl(request.url);sourceUrl(request.licenseUrl);if(request.vocoderUrl)sourceUrl(request.vocoderUrl);}catch(error:any){throw new HttpError(400,error.message);}if(catalog().some(b=>b.availabilityReason==='publisherPermissionRequired'&&b.bundle?.url===sourceUrl(request.url).href))throw new HttpError(403,'publisherPermissionRequired');if(!process.env.DIFFSINGER_COMMAND||!existsSync(process.env.DIFFSINGER_COMMAND))throw new HttpError(503,'singerUnavailable');if(busy||one("SELECT id FROM voice_imports WHERE status='running' AND stage<>'cleanup-failed'")||one("SELECT bank_id FROM voice_library WHERE status='downloading'")||one("SELECT id FROM jobs WHERE kind IN ('render','import') AND status IN ('running','queued')"))throw new HttpError(409,'voiceBusy');if(!cleanInterruptedImports())throw new HttpError(409,'voiceCleanupRequired');const id=randomUUID();run("INSERT INTO voice_imports(id,user_id,request,status,stage) VALUES(?,?,?,'running','queued')",id,userId,JSON.stringify(request));busy=true;void processImport({id,request:JSON.stringify(request)}).catch(error=>log('error','voice.import.cleanup.blocked',{importId:id,error})).finally(()=>{busy=false;});return id;}
function cleanInterruptedImports(){mkdirSync(root,{recursive:true});let clean=true;for(const row of all("SELECT id,bank_id FROM voice_imports WHERE stage IN ('interrupted','cleanup-failed')")){try{const work=folder(row.id),plan=path.join(work,'cleanup.json');if(!row.bank_id&&existsSync(plan))for(const file of JSON.parse(readFileSync(plan,'utf8'))){const relative=path.relative(voiceCache(),file);if(!new RegExp('^[a-f0-9]{64}(\\.files)?(\\.import-'+row.id+')?$').test(relative))throw Error('unsafeCleanupPath');rmSync(file,{recursive:true,force:true});}rmSync(work,{recursive:true,force:true});run("UPDATE voice_imports SET status='failed',stage='interrupted' WHERE id=?",row.id);}catch(error){clean=false;log('error','voice.import.cleanup.failed',{importId:row.id,error});run("UPDATE voice_imports SET status='failed',stage='cleanup-failed',error='Temporary cleanup failed. Retry after the worker releases its files.' WHERE id=?",row.id);}}return clean;}
export function recoverVoiceImports(){const resume=()=>{if(busy)return;const row=all("SELECT * FROM voice_imports WHERE status='running' AND stage<>'cleanup-failed'").find(r=>!workerAlive(r.worker_pid));if(!row)return;if(row.bank_id&&one("SELECT bank_id FROM voice_library WHERE bank_id=? AND status='installed'",row.bank_id)){run("UPDATE voice_imports SET stage='interrupted' WHERE id=?",row.id);if(!cleanInterruptedImports())return;run("UPDATE voice_imports SET status='completed',stage='completed',progress=100,error=NULL WHERE id=?",row.id);return;}run("UPDATE voice_imports SET stage='interrupted' WHERE id=?",row.id);if(!cleanInterruptedImports())return;busy=true;void processImport(row).catch(error=>log('error','voice.import.recovery.failed',{importId:row.id,error})).finally(()=>{busy=false;});};resume();setInterval(resume,10000).unref();}
