import {spawn} from 'node:child_process';
import {existsSync,mkdirSync,readFileSync,writeFileSync,readdirSync,statSync,rmSync,renameSync} from 'node:fs';
import path from 'node:path';
import {log} from './diagnostics.ts';
import {db,dataDir,one,all,run,HttpError} from './db.ts';

db.exec(`CREATE TABLE IF NOT EXISTS voice_library(bank_id TEXT PRIMARY KEY,status TEXT,progress INTEGER DEFAULT 0,bytes INTEGER DEFAULT 0,error TEXT);CREATE TABLE IF NOT EXISTS voice_installs(user_id TEXT REFERENCES users(id) ON DELETE CASCADE,bank_id TEXT,status TEXT,progress INTEGER DEFAULT 0,bytes INTEGER DEFAULT 0,error TEXT,PRIMARY KEY(user_id,bank_id));`);
db.exec(`CREATE TABLE IF NOT EXISTS voice_custom(bank_id TEXT PRIMARY KEY,manifest TEXT NOT NULL);CREATE TABLE IF NOT EXISTS voice_imports(id TEXT PRIMARY KEY,user_id TEXT,request TEXT NOT NULL,status TEXT,stage TEXT,progress INTEGER DEFAULT 0,report TEXT,error TEXT,bank_id TEXT,created TEXT DEFAULT CURRENT_TIMESTAMP,updated TEXT DEFAULT CURRENT_TIMESTAMP);`);
const sourceCatalog=process.env.VOICEBANK_MANIFEST||path.resolve('config/voicebanks.json');
export const catalogPath=path.join(dataDir,'voicebanks-effective.json');
let catalogError='';export function catalog():any[]{try{const banks=JSON.parse(readFileSync(sourceCatalog,'utf8'));if(!Array.isArray(banks)||banks.some(b=>!b.id||!b.name))throw Error('Invalid voice catalog');for(const row of all('SELECT manifest FROM voice_custom')){const b=JSON.parse(row.manifest);if(!banks.some(c=>c.id===b.id))banks.push(b);}const text=JSON.stringify(banks);if(!existsSync(catalogPath)||readFileSync(catalogPath,'utf8')!==text){writeFileSync(catalogPath+'.tmp',text);renameSync(catalogPath+'.tmp',catalogPath);}catalogError='';return banks;}catch(error){if(!catalogError)log('error','voice.catalog.failed',{error,catalogPath});catalogError='catalogUnavailable';return [];}}
export function voiceCache(_userId?:string){return path.join(dataDir,'voices','shared');}
const active=new Map<string,{abort:AbortController,done:Promise<void>}>();
const entries=(bank:any)=>[bank.bundle,bank.vocoderBundle,bank.dictionary].filter(Boolean);
export function publicBanks(userId?:string){let directory:any[]=[];const directoryPath=path.join(path.dirname(sourceCatalog),'voice-directory.json');try{if(existsSync(directoryPath))directory=JSON.parse(readFileSync(directoryPath,'utf8'));}catch(error){log('error','voice.directory.failed',{error});}
 const installedCatalog=catalog();return [...installedCatalog,...directory.filter(b=>!installedCatalog.some(c=>c.id===b.id))].map(bank=>{const installable=bank.installable!==false,state=installable?one('SELECT status,progress,bytes,error FROM voice_library WHERE bank_id=?',bank.id):null;return {id:bank.id,name:bank.name,displayName:bank.displayName,aliases:bank.aliases||[],tags:bank.tags||[],gender:bank.gender||'unspecified',languageCodes:bank.languageCodes||[],version:bank.version,languages:bank.supportedLanguages||['en'],description:bank.description,attribution:bank.attribution,licenseUrl:bank.licenseUrl,source:bank.source||'Qixuan / GitHub',sourceUrl:bank.sourceUrl||bank.licenseUrl,downloadUrl:bank.downloadUrl,downloads:bank.downloads||[],checkedAt:bank.checkedAt,installable,compatibility:installable?'verified':bank.compatibility||'publisher',availabilityReason:bank.availabilityReason,downloadBytes:installable?entries(bank).reduce((n,e)=>n+(e.bytes||0),0):0,...state,status:state?.status||'available'};});}

function size(dir:string):number{if(!existsSync(dir))return 0;const stat=statSync(dir);return stat.isDirectory()?readdirSync(dir).reduce((n,f)=>n+size(path.join(dir,f)),0):stat.size;}
let storageFingerprint='',storageBytes=0;
export function voiceState(userId=''){const banks=publicBanks(userId),canManage=one('SELECT role FROM users WHERE id=?',userId)?.role==='admin';const fingerprint=banks.map(b=>b.id+':'+b.status+':'+b.bytes).join('|');if(fingerprint!==storageFingerprint){storageBytes=size(voiceCache());storageFingerprint=fingerprint;}return {banks,storageBytes,catalogError,catalogCount:banks.length,shared:true,canManage,imports:canManage?all('SELECT * FROM voice_imports ORDER BY created DESC LIMIT 20').map(r=>({...r,request:JSON.parse(r.request),report:r.report?JSON.parse(r.report):null})):[]};}
export function startVoiceInstall(userId:string,id:string){const bank=catalog().find(b=>b.id===id);if(!bank)throw new HttpError(404,'notFound');if(bank.installable===false)throw new HttpError(403,'publisherPermissionRequired');if(active.has(id))throw new HttpError(409,'voiceBusy');if(active.size>=1)throw new HttpError(429,'jobBusy');if(one("SELECT status FROM voice_library WHERE bank_id=? AND status='installed'",id))return voiceState(userId);if(!process.env.DIFFSINGER_COMMAND||!existsSync(process.env.DIFFSINGER_COMMAND))throw new HttpError(503,'singerUnavailable');
 if(one("SELECT id FROM voice_imports WHERE status='running'"))throw new HttpError(409,'voiceBusy');
 if(bank.imported)return installImported(userId,bank);
 const cache=voiceCache(userId);mkdirSync(cache,{recursive:true,mode:0o700});run("INSERT INTO voice_library(bank_id,status) VALUES(?,'downloading') ON CONFLICT(bank_id) DO UPDATE SET status='downloading',progress=0,error=NULL",id);
 log('info','voice.download.started',{userId,bankId:id});const abort=new AbortController();const done=new Promise<void>(resolve=>{let pending='';const child=spawn(process.env.DIFFSINGER_COMMAND!,['--install',id,'--voicebanks',catalogPath,'--cache',cache],{signal:abort.signal,windowsHide:true,stdio:['ignore','pipe','pipe']});
 child.stdout.on('data',chunk=>{pending+=chunk.toString();const lines=pending.split('\n');pending=lines.pop()!;for(const line of lines){try{const event=JSON.parse(line);if(Number.isFinite(event.progress))run('UPDATE voice_library SET progress=? WHERE bank_id=?',Math.max(0,Math.min(99,event.progress)),id);}catch{}}});child.stderr.on('data',chunk=>log('debug','voice.download.output',{userId,bankId:id},chunk.toString()));
 let ended=false;const finish=(ok:boolean)=>{if(ended)return;ended=true;const bytes=entries(bank).reduce((n,e)=>n+size(path.join(cache,e.sha256))+size(path.join(cache,e.sha256+'.files')),0);run('UPDATE voice_library SET status=?,progress=?,bytes=?,error=? WHERE bank_id=?',ok?'installed':'failed',ok?100:0,bytes,ok?null:abort.signal.aborted?'cancelled':'downloadFailed',id);active.delete(id);log(ok?'info':'error','voice.download.finished',{userId,bankId:id,ok,bytes,cancelled:abort.signal.aborted});resolve();};child.once('error',error=>{log('error','voice.download.failed',{userId,bankId:id,error});if(!child.pid)finish(false);});child.once('close',code=>finish(code===0));});active.set(id,{abort,done});return voiceState(userId);
}
export async function removeVoice(userId:string,id:string){if(one('SELECT role FROM users WHERE id=?',userId)?.role!=='admin')throw new HttpError(403,'adminRequired');const bank=catalog().find(b=>b.id===id);if(!bank)throw new HttpError(404,'notFound');if(one("SELECT id FROM jobs WHERE kind='render' AND status IN ('queued','running')"))throw new HttpError(409,'voiceInUse');const install=active.get(id);if(install){install.abort.abort();await install.done;}
 if(one("SELECT id FROM voice_imports WHERE status='running'"))throw new HttpError(409,'voiceBusy');
 const other=new Set(all("SELECT bank_id FROM voice_library WHERE bank_id<>? AND status='installed'",id).flatMap(row=>entries(catalog().find(b=>b.id===row.bank_id)||{}).map(e=>e.sha256)));const cache=voiceCache(userId);
 for(const e of entries(bank)){if(other.has(e.sha256))continue;if(!/^[a-f0-9]{64}$/i.test(e.sha256))throw new Error('invalidAssetHash');for(const suffix of ['','.files','.partial']){const target=path.resolve(cache,e.sha256+suffix);if(!target.startsWith(path.resolve(cache)+path.sep))throw new Error('assetPath');rmSync(target,{recursive:true,force:true});}}
 run('DELETE FROM voice_library WHERE bank_id=?',id);log('info','voice.removed',{userId,bankId:id});return voiceState(userId);
}
function installImported(userId:string,bank:any){const id=bank.id,cache=voiceCache(),abort=new AbortController();mkdirSync(cache,{recursive:true});run("INSERT INTO voice_library(bank_id,status) VALUES(?,'downloading') ON CONFLICT(bank_id) DO UPDATE SET status='downloading',error=NULL,progress=0",id);const done=(async()=>{try{const {downloadVoice}=await import('./voice-download.ts');for(const entry of entries(bank)){const file=path.join(cache,entry.sha256);if(!existsSync(file))await downloadVoice(entry.url,file,(bytes,total)=>run('UPDATE voice_library SET progress=? WHERE bank_id=?',total?Math.floor(bytes/total*90):0,id),entry.sha256,abort.signal);}await new Promise<void>((resolve,reject)=>{const child=spawn(process.env.DIFFSINGER_COMMAND!,['--install',id,'--voicebanks',catalogPath,'--cache',cache],{windowsHide:true,signal:abort.signal,stdio:['ignore','ignore','pipe']});child.stderr.on('data',chunk=>log('debug','voice.download.output',{bankId:id},chunk.toString()));child.on('error',reject);child.on('close',code=>code===0?resolve():reject(Error('nativeValidationFailed')));});run("UPDATE voice_library SET status='installed',progress=100,bytes=?,error=NULL WHERE bank_id=?",entries(bank).reduce((n,e)=>n+size(path.join(cache,e.sha256))+size(path.join(cache,e.sha256+'.files')),0),id);}catch(error){log('error','voice.download.failed',{userId,bankId:id,error});run("UPDATE voice_library SET status='failed',error=?,progress=0 WHERE bank_id=?",abort.signal.aborted?'cancelled':'downloadFailed',id);}finally{active.delete(id);}})();active.set(id,{abort,done});return voiceState(userId);}
export function requireVoices(userId:string,score:any){const banks=catalog();for(const id of new Set(score.parts.filter((p:any)=>p.notes.some((n:any)=>n.pitch!==null)).map((p:any)=>p.voicebank))){if(!id||!banks.some(b=>b.id===id&&b.installable!==false)||!one("SELECT bank_id FROM voice_library WHERE bank_id=? AND status='installed'",id))throw new HttpError(409,'voiceNotInstalled');}}
export function recoverVoiceInstalls(){migrateSharedVoices();run("UPDATE voice_library SET status='failed',error='interrupted' WHERE status='downloading'");}
export function migrateSharedVoices(){
 const root=path.resolve(dataDir,'voices'),target=voiceCache();mkdirSync(target,{recursive:true});
 for(const row of all("SELECT * FROM voice_installs WHERE status='installed'")){
  if(!/^[A-Za-z0-9_-]+$/.test(row.user_id))continue;const bank=catalog().find(b=>b.id===row.bank_id);if(!bank)continue;
  try{for(const asset of entries(bank)){if(!/^[a-f0-9]{64}$/i.test(asset.sha256))throw Error('invalidAssetHash');for(const suffix of ['','.files']){const source=path.resolve(root,row.user_id,asset.sha256+suffix),destination=path.resolve(target,asset.sha256+suffix);if(!source.startsWith(root+path.sep)||!destination.startsWith(path.resolve(target)+path.sep))throw Error('assetPath');if(existsSync(source)&&!existsSync(destination))renameSync(source,destination);}}
   const complete=entries(bank).every(e=>existsSync(path.join(target,e.sha256))&&(!e.archive||existsSync(path.join(target,e.sha256+'.files'))));if(!complete)throw Error('incompleteLegacyVoice');run("INSERT OR IGNORE INTO voice_library(bank_id,status,progress,bytes) VALUES(?,'installed',100,?)",bank.id,row.bytes||0);run('DELETE FROM voice_installs WHERE user_id=? AND bank_id=?',row.user_id,bank.id);log('info','voice.shared.migrated',{bankId:bank.id});
  }catch(error){log('error','voice.shared.migration.failed',{bankId:bank.id,error});}
 }
}
