import { z } from 'zod';
import { XMLParser } from 'fast-xml-parser';
import { unzipSync, strFromU8, zipSync, strToU8 } from 'fflate';
export const PPQ=480;
export const voiceTypes=[['soprano','女高音',60,84],['mezzo','次女高音',57,81],['alto','女低音',53,77],['contralto','低女低音',52,76],['countertenor','假聲男高音',55,79],['tenor','男高音',48,72],['baritone','男中音',45,69],['bass','男低音',40,64],['treble','高音聲部',60,81],['custom','自訂',36,88]] as const;
export const styles=[['choral','古典合唱','Classical choral'],['renaissance','文藝復興複音','Renaissance'],['baroque','巴洛克','Baroque'],['romantic','浪漫派','Romantic'],['contemporary','當代合唱','Contemporary choir'],['hymn','聖詠','Hymn / chorale'],['gospel','福音','Gospel'],['spiritual','靈歌','Spiritual'],['barbershop','理髮店四重唱','Barbershop'],['jazz','爵士人聲','Vocal jazz'],['swing','搖擺','Swing'],['acappella','現代無伴奏','Contemporary a cappella'],['pop','流行','Pop'],['rock','搖滾','Rock'],['soul','節奏藍調／靈魂','R&B / soul'],['folk','民謠／傳統','Folk / traditional'],['theatre','音樂劇','Musical theatre'],['cinematic','電影配樂','Cinematic'],['chant','吟唱','Chant'],['ambient','極簡／氛圍','Minimalist / ambient']] as const;
export const textures=[['homophonic','和聲齊唱','Block harmony'],['close','密集和聲','Close harmony'],['open','開放排列','Open voicing'],['counterpoint','對位','Counterpoint'],['canon','輪唱','Canon'],['response','呼應','Call & response'],['antiphonal','交替合唱','Antiphonal'],['drone','持續低音','Drone'],['backing','主唱與和聲','Lead & backing'],['build','由齊唱漸入和聲','Unison to harmony']] as const;
export const wordlessModes=['ah','woo','ba','da','scat'] as const;
const safeId=z.string().min(1).max(100).regex(/^[A-Za-z0-9_-]+$/);
export const noteSchema=z.object({id:safeId,pitch:z.number().int().min(0).max(127).nullable(),start:z.number().int().min(0),duration:z.number().int().positive(),lyric:z.string().max(100).default(''),syllabic:z.enum(['single','begin','middle','end']).default('single'),tie:z.enum(['none','start','stop','continue']).default('none'),locked:z.boolean().default(false)});
export const partSchema=z.object({id:safeId,name:z.string().min(1).max(80),type:z.string(),low:z.number().int().min(0).max(127),high:z.number().int().min(0).max(127),voicebank:z.string().default(''),wordless:z.enum(wordlessModes).default('ah'),gain:z.number().min(0).max(2).default(.8),muted:z.boolean().default(false),notes:z.array(noteSchema).max(12000)});
export const barlineSchema=z.object({bar:z.number().int().positive(),location:z.enum(["left","right"]),repeat:z.enum(["forward","backward"]).optional(),times:z.number().int().min(2).max(8).optional(),endingType:z.enum(["start","stop","discontinue"]).optional(),endingNumbers:z.array(z.number().int().min(1).max(8)).optional()});
export const scoreSchema=z.object({barlines:z.array(barlineSchema).max(2000).optional(),title:z.string().min(1).max(200),composer:z.string().max(200).default(''),tempo:z.number().min(20).max(300),beats:z.number().int().min(1).max(16),beatType:z.union([z.literal(2),z.literal(4),z.literal(8),z.literal(16)]),key:z.number().int().min(-7).max(7),leadId:safeId,parts:z.array(partSchema).min(1).max(24),styles:z.array(z.string()).max(30),textures:z.array(z.string()).max(20).default([]),lyricsLanguage:z.string().default('en'),tempoMap:z.array(z.object({tick:z.number().int().min(0),bpm:z.number().min(20).max(300)})).default([])});
export type Score=z.infer<typeof scoreSchema>; export type Part=z.infer<typeof partSchema>; export type Note=z.infer<typeof noteSchema>;
export const singingKey=(s:Score)=>JSON.stringify({barlines:s.barlines,tempo:s.tempo,tempoMap:s.tempoMap,parts:s.parts.map(({id,voicebank,wordless,notes})=>({id,voicebank,wordless,notes}))});
export const uid=()=>'u'+globalThis.crypto.randomUUID();
export const barTicks=(s:Score)=>PPQ*4/s.beatType*s.beats;
export const endTick=(s:Score)=>Math.max(barTicks(s),...s.parts.flatMap(p=>p.notes.map(n=>n.start+n.duration)));
export const pitchName=(n:number|null)=>n===null?'Rest':`${['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][n%12]}${Math.floor(n/12)-1}`;
export function createPart(type='soprano'):Part {const v=voiceTypes.find(v=>v[0]===type)||voiceTypes[0];return {id:uid(),type,name:type[0].toUpperCase()+type.slice(1),low:v[2],high:v[3],voicebank:'',wordless:'ah',gain:.8,muted:false,notes:[]};}
export function newScore(title='新的旋律'):Score {const p=createPart();return {title,composer:'',tempo:88,beats:4,beatType:4,key:0,leadId:p.id,parts:[p],styles:['choral'],textures:['homophonic'],lyricsLanguage:'en',tempoMap:[]};}
export function demoScore():Score {const s=newScore('晨光 · Morning light');s.composer='Choirloom';s.parts[0].notes=[60,64,67,69,67,64,62,60,62,65,69,67,64,62,60,60].map((pitch,i)=>({id:uid(),pitch,start:i*480,duration:480,lyric:['mor','ning','light','','fills','the','sky','','sing','a','gain','','soft','and','clear',''][i],syllabic:i===0?'begin':i===1?'end':'single',tie:'none',locked:false}));return s;}
export type Finding={severity:'error'|'warning',code:string,partId?:string,noteId?:string};
export function validateScore(score:Score,previous?:Score,preserveLead=true):Finding[]{const out:Finding[]=[];const ids=new Set<string>();if(!score.parts.some(p=>p.id===score.leadId))out.push({severity:'error',code:'leadMissing'});
 for(const p of score.parts){if(ids.has(p.id))out.push({severity:'error',code:'duplicateId'});ids.add(p.id);if(p.low>p.high)out.push({severity:'error',code:'range',partId:p.id});let last:Note|undefined;
 for(const n of [...p.notes].sort((a,b)=>a.start-b.start)){if(ids.has(n.id))out.push({severity:'error',code:'duplicateId'});ids.add(n.id);if(n.start+n.duration>PPQ*4*1000)out.push({severity:'error',code:'tooLong'});if(last&&n.start<last.start+last.duration)out.push({severity:'error',code:'overlap',partId:p.id,noteId:n.id});if(n.pitch!==null&&(n.pitch<p.low||n.pitch>p.high))out.push({severity:'warning',code:'range',partId:p.id,noteId:n.id});if(last?.pitch!=null&&n.pitch!=null&&Math.abs(last.pitch-n.pitch)>9)out.push({severity:'warning',code:'leap',partId:p.id,noteId:n.id});if(['stop','continue'].includes(n.tie)&&(!last||last.pitch!==n.pitch||last.start+last.duration!==n.start||!['start','continue'].includes(last.tie)))out.push({severity:'error',code:'tie',partId:p.id,noteId:n.id});if(last&&['start','continue'].includes(last.tie)&&(last.pitch!==n.pitch||last.start+last.duration!==n.start||!['stop','continue'].includes(n.tie)))out.push({severity:'error',code:'tie',partId:p.id,noteId:last.id});last=n;}if(last&&['start','continue'].includes(last.tie))out.push({severity:'error',code:'tie',partId:p.id,noteId:last.id});}
 if(previous){const old=previous.parts.find(p=>p.id===previous.leadId);const lead=score.parts.find(p=>p.id===previous.leadId);const musical=(p:Part|undefined)=>p?.notes.map(({id,pitch,start,duration,lyric,tie})=>({id,pitch,start,duration,lyric,tie}));if(preserveLead&&JSON.stringify(musical(old))!==JSON.stringify(musical(lead)))out.push({severity:'error',code:'leadChanged'});for(const p of previous.parts)for(const n of p.notes.filter(n=>n.locked)){const current=score.parts.find(x=>x.id===p.id)?.notes.find(x=>x.id===n.id);if(JSON.stringify(n)!==JSON.stringify(current))out.push({severity:'error',code:'lockedChanged',noteId:n.id});}}
 return out;
}
const escape=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));
function notationDuration(ticks:number){const types:[[number,string],...Array<[number,string]>]=[[1920,'whole'],[960,'half'],[480,'quarter'],[240,'eighth'],[120,'16th'],[60,'32nd'],[30,'64th']];for(const [n,type] of types){if(ticks===n)return `<type>${type}</type>`;if(ticks===n*1.5)return `<type>${type}</type><dot/>`;}return '';}
export function wordlessLyrics(p:Part):Map<string,string>{let index=0;let end=-1;const map=new Map<string,string>();for(const n of [...p.notes].sort((a,b)=>a.start-b.start)){if(n.start>end)index=0;if(n.pitch===null){index=0;continue;}const tied=['stop','continue'].includes(n.tie);map.set(n.id,n.lyric||(tied?'':p.wordless==='ah'?'ah':p.wordless==='woo'?'woo':p.wordless==='ba'?['ba','ba','bom'][index%3]:p.wordless==='da'?['da','da','dum'][index%3]:['doo','ba','dap','doo','bwee','bom'][index%6]));if(!tied)index++;end=n.start+n.duration;}return map;}
export function toMusicXML(s:Score,underlay=false):string {const bt=barTicks(s),count=Math.ceil(endTick(s)/bt);return `<?xml version="1.0" encoding="utf-8"?><score-partwise version="4.0"><work><work-title>${escape(s.title)}</work-title></work><identification><creator type="composer">${escape(s.composer)}</creator></identification><part-list>${s.parts.map(p=>`<score-part id="${escape(p.id)}"><part-name>${escape(p.name)}</part-name></score-part>`).join('')}</part-list>${s.parts.map(p=>{const lyrics=wordlessLyrics(p);return `<part id="${escape(p.id)}">${Array.from({length:count},(_,bar)=>{const start=bar*bt;let cursor=start;let body='';const rest=(dur:number)=>`<note><rest/><duration>${dur}</duration>${notationDuration(dur)}</note>`;
 for(const n of [...p.notes].sort((a,b)=>a.start-b.start).filter(n=>n.start<start+bt&&n.start+n.duration>start)){const onset=Math.max(n.start,start),dur=Math.min(n.start+n.duration,start+bt)-onset;if(onset>cursor)body+=rest(onset-cursor);const stop=n.start<start||['stop','continue'].includes(n.tie),begin=n.start+n.duration>start+bt||['start','continue'].includes(n.tie);let pitch='<rest/>';if(n.pitch!==null){const step=['C','C','D','D','E','F','F','G','G','A','A','B'][n.pitch%12];pitch=`<pitch><step>${step}</step>${[1,3,6,8,10].includes(n.pitch%12)?'<alter>1</alter>':''}<octave>${Math.floor(n.pitch/12)-1}</octave></pitch>`;}const lyric=underlay?lyrics.get(n.id):n.lyric;body+=`<note id="${escape(n.id)}${stop?'-t'+bar:''}">${pitch}<duration>${dur}</duration>${stop?'<tie type="stop"/>':''}${begin?'<tie type="start"/>':''}${notationDuration(dur)}${begin||stop?`<notations>${stop?'<tied type="stop"/>':''}${begin?'<tied type="start"/>':''}</notations>`:''}${lyric&&!stop?`<lyric><syllabic>${n.syllabic}</syllabic><text>${escape(lyric)}</text></lyric>`:''}</note>`;cursor=onset+dur;}
 if(cursor<start+bt)body+=rest(start+bt-cursor);return `<measure number="${bar+1}">${bar===0?`<attributes><divisions>${PPQ}</divisions><key><fifths>${s.key}</fifths></key><time><beats>${s.beats}</beats><beat-type>${s.beatType}</beat-type></time><clef><sign>${p.high<74?'F':'G'}</sign><line>${p.high<74?4:2}</line></clef></attributes>`:''}${(bar===0?[{tick:0,bpm:s.tempo}]:[]).concat(s.tempoMap.filter(t=>t.tick>=start&&t.tick<start+bt)).map(t=>`<direction><direction-type><metronome><beat-unit>quarter</beat-unit><per-minute>${t.bpm}</per-minute></metronome></direction-type><offset>${t.tick-start}</offset><sound tempo="${t.bpm}"/></direction>`).join('')}${(s.barlines||[]).filter(m=>m.bar===bar+1&&m.location==='left').map(m=>`<barline location="${m.location}">${m.endingType?`<ending number="${(m.endingNumbers||[1]).join(",")}" type="${m.endingType}"/>`:""}${m.repeat?`<repeat direction="${m.repeat}"${m.times?` times="${m.times}"`:""}/>`:""}</barline>`).join('')}${body}${(s.barlines||[]).filter(m=>m.bar===bar+1&&m.location==='right').map(m=>`<barline location="${m.location}">${m.endingType?`<ending number="${(m.endingNumbers||[1]).join(",")}" type="${m.endingType}"/>`:""}${m.repeat?`<repeat direction="${m.repeat}"${m.times?` times="${m.times}"`:""}/>`:""}</barline>`).join('')}${bar===count-1&&!(s.barlines||[]).some(m=>m.bar===bar+1&&m.location==='right')?'<barline location="right"><bar-style>light-heavy</bar-style></barline>':''}</measure>`;}).join('')}</part>`;}).join('')}</score-partwise>`;}
export function toMXL(s:Score){return zipSync({'META-INF/container.xml':strToU8('<?xml version="1.0"?><container><rootfiles><rootfile full-path="score.musicxml" media-type="application/vnd.recordare.musicxml+xml"/></rootfiles></container>'),'score.musicxml':strToU8(toMusicXML(s))});}
const list=(v:any):any[]=>v==null?[]:Array.isArray(v)?v:[v];
export function readMXL(bytes:Uint8Array):string{const files=unzipSync(bytes,{filter:f=>f.originalSize<8_000_000&&!f.name.includes('..')&&!f.name.startsWith('/')});const keys=Object.keys(files).filter(k=>!k.startsWith('META-INF/')&&/\.(musicxml|xml)$/i.test(k));if(!keys.length)throw Error('invalidImport');return strFromU8(files[keys[0]]);}
export function fromMusicXML(xml:string,partIds?:string[],importFindings:Finding[]=[]):Score{if(xml.length>8_000_000||/<!ENTITY/i.test(xml)||/<!DOCTYPE[^>]*\[/i.test(xml))throw Error('invalidImport');const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false});const root=parser.parse(xml)['score-partwise'];if(!root)throw Error('invalidImport');const score=newScore(String(root.work?.['work-title']||root['movement-title']||'Imported score'));score.parts=[];score.composer=String((list(root.identification?.creator).find((c:any)=>c['@_type']==='composer')||list(root.identification?.creator)[0])?.['#text']||'');const names=new Map(list(root['part-list']?.['score-part']).map((p:any)=>[p['@_id'],p['part-name']]));
 const ordered=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',preserveOrder:true,parseTagValue:false}).parse(xml).find((x:any)=>x['score-partwise'])?.['score-partwise'];
 for(const raw of list(root.part)){if(partIds&&!partIds.includes(raw['@_id']))continue;let divisions=PPQ,tick=0;const sourceVoices=new Map<string,string>();const p=createPart();p.name=String(names.get(raw['@_id'])||'Voice');const orderedPart=ordered?.find((x:any)=>x.part&&x[':@']?.['@_id']===raw['@_id']);const measures=orderedPart?.part.filter((x:any)=>x.measure)||[];
 for(let mi=0;mi<list(raw.measure).length;mi++){const m=list(raw.measure)[mi];if(!score.parts.length){for(const b of list(m.barline)){const repeat=b.repeat?.['@_direction'],ending=b.ending;if(repeat||ending)(score.barlines??=[]).push({bar:mi+1,location:b['@_location']==='left'?'left':'right',...(repeat?{repeat,times:Math.max(2,Math.min(8,Number(b.repeat['@_times'])||2))}:{}),...(ending?{endingType:ending['@_type'],endingNumbers:String(ending['@_number']||'1').split(/[, ]+/).flatMap(v=>{const [a,b]=v.split('-').map(Number);return b?Array.from({length:Math.min(8,b-a+1)},(_,i)=>a+i):[a];}).filter(n=>n>=1&&n<=8)}:{})});}}const attr=list(m.attributes)[0];if(attr?.divisions)divisions=Number(attr.divisions);if(attr?.time){score.beats=Number(attr.time.beats);score.beatType=Number(attr.time['beat-type']) as Score['beatType'];}if(attr?.key)score.key=Number(attr.key.fifths||0);let cursor=tick,max=tick,chordStart=tick;for(const d of list(m.direction)){const bpm=Number(d.sound?.['@_tempo']||d['direction-type']?.metronome?.['per-minute']);if(bpm){if(mi===0)score.tempo=bpm;else score.tempoMap.push({tick,bpm});}}
 const entries=measures[mi]?.measure||[];const rawNotes=list(m.note);let noteIndex=0;for(const item of entries){if(item.backup){const duration=Number(item.backup.find((x:any)=>x.duration)?.duration[0]['#text']);cursor-=Math.round(duration/divisions*PPQ);}if(item.forward){const duration=Number(item.forward.find((x:any)=>x.duration)?.duration[0]['#text']);cursor+=Math.round(duration/divisions*PPQ);}if(!item.note)continue;const obj=rawNotes[noteIndex++];if(obj.grace!==undefined)continue;const duration=Math.round(Number(obj.duration||0)/divisions*PPQ);if(!duration)continue;const chord=obj.chord!==undefined;if(!chord)chordStart=cursor;const midi=obj.rest!==undefined?null:(Number(obj.pitch?.octave)+1)*12+({C:0,D:2,E:4,F:5,G:7,A:9,B:11}[obj.pitch?.step as 'C']||0)+Number(obj.pitch?.alter||0);const lyric=list(obj.lyric)[0];const ties=list(obj.tie).map(t=>t['@_type']);p.notes.push({id:uid(),pitch:midi,start:chord?chordStart:cursor,duration,lyric:String(lyric?.text||''),syllabic:lyric?.syllabic||'single',tie:ties.length===2?'continue':ties[0]||'none',locked:false});sourceVoices.set(p.notes.at(-1)!.id,String(obj.staff||'1')+':'+String(obj.voice||'1'));if(!chord)cursor+=duration;max=Math.max(max,(chord?chordStart:cursor-duration)+duration);}tick=m['@_implicit']==='yes'?max:Math.max(max,tick+barTicks(score));}
 if(p.notes.length){const sounding=p.notes.filter(n=>n.pitch!==null);p.low=Math.min(60,...sounding.map(n=>n.pitch!));p.high=Math.max(72,...sounding.map(n=>n.pitch!));score.parts.push(...splitImportedPart(p,importFindings,sourceVoices));}}
 if(!score.parts.length)throw Error('emptyScore');score.leadId=score.parts[0].id;return scoreSchema.parse(score);
}
// MusicXML can encode divisi and duplicate rests in one staff. Keep every
// sounding note in a non-overlapping lane; silence is represented by gaps.
function splitImportedPart(part:Part,findings:Finding[],voices:Map<string,string>):Part[]{
 const sounding=part.notes.filter(n=>n.pitch!==null).sort((a,b)=>a.start-b.start);
 const lanes:Part[]=[],laneVoices=new Map<string,string>();
 for(const note of sounding){
  const available=lanes.filter(p=>{const last=p.notes.at(-1)!;return laneVoices.get(p.id)===voices.get(note.id)&&last.start+last.duration<=note.start;});
  const tied=available.find(p=>{const last=p.notes.at(-1)!;return ['stop','continue'].includes(note.tie)&&last.pitch===note.pitch&&last.start+last.duration===note.start&&['start','continue'].includes(last.tie);});
  const lane=tied||available[0]||(()=>{const p={...part,id:lanes.length?uid():part.id,notes:[] as Note[]};lanes.push(p);laneVoices.set(p.id,voices.get(note.id)!);return p;})();lane.notes.push(note);
 }
 if(lanes.length>24&&new Set(voices.values()).size>1){findings.push({severity:'warning',code:'importPackedVoices',partId:part.id});return splitImportedPart(part,findings,new Map(part.notes.map(n=>[n.id,'1'])));}
 if(!lanes.length)lanes.push({...part,notes:[]});
 // Restore explicit rests only where they do not cover a sounding note.
 const rests:Note[]=[];
 for(const rest of part.notes.filter(n=>n.pitch===null).sort((a,b)=>a.start-b.start)){
  const last=rests.at(-1);if(last&&rest.start<=last.start+last.duration)last.duration=Math.max(last.start+last.duration,rest.start+rest.duration)-last.start;else rests.push({...rest});
 }
 const target=lanes[0];for(const rest of rests){let at=rest.start;const end=rest.start+rest.duration;for(const note of target.notes.filter(n=>n.pitch!==null)){if(note.start>=end)break;if(note.start+note.duration<=at)continue;if(note.start>at)target.notes.push({...rest,id:uid(),start:at,duration:note.start-at});at=Math.max(at,note.start+note.duration);}if(at<end)target.notes.push({...rest,id:uid(),start:at,duration:end-at});}target.notes.sort((a,b)=>a.start-b.start);
 if(lanes.length>1)findings.push({severity:'warning',code:'importSplitVoices',partId:part.id});
 for(const [index,lane] of lanes.entries()){
  if(lanes.length>1)lane.name=part.name+' · '+(index+1);
  const ties=lane.notes.map(n=>n.tie);
  for(let i=0;i<lane.notes.length;i++){const n=lane.notes[i],prev=lane.notes[i-1],next=lane.notes[i+1];const stop=['stop','continue'].includes(ties[i])&&prev?.pitch===n.pitch&&prev.start+prev.duration===n.start&&['start','continue'].includes(ties[i-1]);const start=['start','continue'].includes(ties[i])&&next?.pitch===n.pitch&&n.start+n.duration===next.start&&['stop','continue'].includes(ties[i+1]);const tie=stop&&start?'continue':stop?'stop':start?'start':'none';if(tie!==n.tie)findings.push({severity:'warning',code:'importTieRepaired',partId:lane.id,noteId:n.id});n.tie=tie;}
 }
 return lanes;
}
function orderedToXML(entries:any[]):string{return entries.map(entry=>{if('#text'in entry)return escape(String(entry['#text']));const key=Object.keys(entry).find(k=>k!==':@')!;const attrs=Object.entries(entry[':@']||{}).map(([k,v])=>` ${k.slice(2)}="${escape(String(v))}"`).join('');return `<${key}${attrs}>${orderedToXML(entry[key]||[])}</${key}>`;}).join('');}
