import json,urllib.request,re,html
from pathlib import Path
rows=[]
def add(id,name,source,url,languages,gender='unspecified',version='',download=None,tags=[]):
 rows.append(dict(id=id,name=name,version=version,source=source,sourceUrl=url,downloadUrl=download or url,licenseUrl=url,languageCodes=languages,supportedLanguages=languages,gender=gender,tags=tags,aliases=[name,source,*languages],attribution=source,installable=False,compatibility='publisher',checkedAt='2026-09-08',description={'en':'Publisher download; not yet verified for Choirloom rendering.','zh-Hant':'可從發布者下載；尚未驗證 Choirloom 合成相容性。'}))
for id,name,langs,gender,version in [('printto-v5','Printto Magicbeat V5',['en','th','ja','fr','ru','ko','es','zh','id','fil'],'male','5.3.0'),('tanya','Tanya Magicbeat',['en','th','ja','fr','ru','ko','es','zh','id','fil'],'female','4.0.0'),('kaiz','Kaiz',['en','th','ja','fr','ru','ko','es','zh','id','fil'],'male','V2'),('francefrank','FranceFrank',['en','th','ja'],'male',''),('petchploy','Petchploy',['th','en','ja','fr'],'unspecified','1.0.1')]:
 slug='printto' if id.startswith('printto') else id;add(id,name,'PRINTmov','https://printmov.com/'+slug,langs,gender,version)
add('printto-pure','Printto Magicbeat V5 Pure','PRINTmov','https://printmov.com/printto',['th','ja','en'],'male','1.0.0',tags=['commercial pack'])
add('printto-millefeuille','Printto Magicbeat Millefeuille','PRINTmov / UTAU France','https://printmov.com/printto',['zh','en','fr','de','it','ja','ko','pl','pt','ru','es','th'],'male','2.0.0')
add('ada-synphonia','Ada Synphonia','PRINTmov','https://printmov.com/singers',['en','th','ja','fr','ru','ko','es','zh','id','fil'],'unspecified','1.0.2',download='https://printmov.com/diff-th-plugin-install?vb-link=1F1mkKL9N3BujWxLTzRed5Y6TKC1MFXhG&vb-name=Ada%20Synphonia')
repos=[('ria','Ria','RibosomeK/RiaDiffSinger',['yue','zh','ja'],'unspecified'),('tiger','TIGER','spicytigermeat/tiger_diffsinger',['en','ja','es','fr','ko'],'male'),('canary','Canary','spicytigermeat/canary_diffsinger',['en','ja','fr','ko'],'male'),('nishiren','Nishiren Gard','Gardanana/Nishiren-AI-Diffsinger',['en','ja','zh','ko','es','it','fr','th'],'unspecified'),('umidaji','Umidaji','Team-BRAPA/Umidaji-DiffSinger',['pt'],'unspecified'),('liee','LIEE · Immortal Idol','julieraptor/DIFFSINGER-LIEE-Immortal-Idol',['en','ja','pl','fr','vi','zh','es','fil'],'unspecified')]
for id,name,repo,langs,gender in repos:
 data=json.load(urllib.request.urlopen('https://api.github.com/repos/'+repo+'/releases',timeout=30));r=next(r for r in data if not r['draft'] and r['assets']);add(id,name,repo.split('/')[0],'https://github.com/'+repo,langs,gender,r['tag_name'],r['html_url']);rows[-1]['releaseApi']='https://api.github.com/repos/'+repo+'/releases';rows[-1]['downloads']=[{'name':a['name'],'url':a['browser_download_url'],'bytes':a['size']} for a in r['assets'] if a['name'].lower().endswith(('.zip','.7z','.rar'))]
add('leif','Leif','JaimeSynth / TigerMeat','https://leifly.carrd.co/',['en','ja','es','fr','it','pt','zh','ko'],'male',tags=['soft','power','deep'])
add('neurosynth','NeuroSynth','NeuroSynth Project','https://neuros.click/neuro-synth/',['en','ja'],tags=['B2-G6','noncommercial'])
Path('config/voice-directory.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(len(rows),'publisher voices indexed')
