import {useState} from 'react';
import {useLiveEvent} from './live';
type Props={locale:string,user:any,filter:any,onFilter:(f:any)=>void,api:(url:string,method?:string,body?:any)=>Promise<any>,onOpen:(id:string)=>void};
export function AdminConsole({locale,user,filter,onFilter,api,onOpen}:Props){
 const t=(zh:string,en:string)=>locale==='en'?en:zh,[tab,setTab]=useState('logs'),[data,setData]=useState<any>(null),[entries,setEntries]=useState<any[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState('');
 useLiveEvent('admin',s=>{setData(s);setEntries(s.logs);});useLiveEvent('log',e=>setEntries(old=>[e,...old.filter(x=>x.id!==e.id)].slice(0,300)));
 async function role(id:string,value:string){setBusy(id);setError('');try{await api(`/admin/users/${id}/role`,'PATCH',{role:value});}catch(e:any){setError(e.message==='lastAdmin'?t('至少須保留一位管理員。','At least one administrator must remain.'):t('無法更新權限。','Could not update the role.'));}finally{setBusy('');}}
 const matches=(row:any)=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase());
 return <div className="admin-console"><div className="eyebrow">CHOIRLOOM ADMINISTRATION</div><h2>{t('管理中心','Admin console')}</h2><div className="library-tabs">{[['logs',t('即時診斷','Live diagnostics')],['users',t('使用者與權限','Users & roles')],['works',t('所有作品','All works')]].map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<p role="alert" className="library-error">{error}</p>}
 {!data?<p role="status">{t('等待 WebSocket 同步…','Waiting for WebSocket sync…')}</p>:<>{tab==='logs'&&<><div className="admin-health"><span>Node {data.health.node}</span><span>{data.health.memoryMB} MB</span><span>{t('工作中','Active')}: {data.health.worker.active.length}</span><span>{t('佇列','Queued')}: {data.health.worker.queued}</span></div><div className="admin-filters"><input aria-label={t('搜尋診斷紀錄','Search logs')} placeholder={t('搜尋事件、錯誤或請求 ID','Search events, errors or request ID')} value={filter.query||''} onChange={e=>onFilter({...filter,query:e.target.value})}/><select aria-label={t('紀錄等級','Log level')} value={filter.level||''} onChange={e=>onFilter({...filter,level:e.target.value})}>{['','debug','info','warn','error'].map(v=><option key={v} value={v}>{v||t('所有等級','All levels')}</option>)}</select><select aria-label={t('紀錄來源','Log source')} value={filter.source||''} onChange={e=>onFilter({...filter,source:e.target.value})}><option value="">{t('所有來源','All sources')}</option><option value="server">{t('伺服器','Server')}</option><option value="client">{t('瀏覽器','Browser')}</option></select></div><details className="admin-jobs"><summary>{t('工作紀錄（點選以追蹤診斷）','Job history (select to trace diagnostics)')}</summary>{data.jobs.map((j:any)=><button key={j.id} onClick={()=>onFilter({...filter,jobId:j.id,query:''})}><span>{j.title} · {j.kind}</span><small>{j.status} / {j.stage} · {j.id}</small></button>)}</details>{filter.jobId&&<button onClick={()=>onFilter({...filter,jobId:''})}>{t('清除工作篩選','Clear job filter')} × {filter.jobId}</button>}<p className="muted small">{t('紀錄即時串流，保留最多約 20,000 筆或 14 天。密碼、權杖與提示內容會遮蔽。','Logs stream live and are retained for up to about 20,000 entries or 14 days. Passwords, tokens and prompt contents are redacted.')}</p><div className="log-list">{entries.map(e=><details key={e.id} className={'log-entry '+e.level}><summary><time>{new Date(e.time).toLocaleString(locale)}</time><b>{e.level}</b><span className="log-source">{e.source}</span><span>{e.event}</span></summary>{e.message&&<p>{e.message}</p>}<pre>{JSON.stringify(e.context,null,2)}</pre></details>)}{!entries.length&&<p className="muted">{t('沒有符合條件的紀錄。','No matching logs.')}</p>}</div>{entries.length>0&&<button onClick={()=>void api('/admin/logs?'+new URLSearchParams({...filter,before:String(Math.min(...entries.map(e=>e.id)))})).then(rows=>setEntries(old=>[...old,...rows.filter((r:any)=>!old.some(e=>e.id===r.id))])).catch(()=>setError(t('無法載入較早紀錄。','Could not load older logs.')))}>{t('載入較早紀錄','Load older logs')}</button>}</>}
 {tab!=='logs'&&<input aria-label={t('搜尋','Search')} placeholder={t('搜尋名稱、電子郵件或作品','Search name, email or title')} value={query} onChange={e=>setQuery(e.target.value)}/>}
 {tab==='users'&&<div className="admin-rows">{data.users.filter(matches).map((u:any)=><div key={u.id}><span><strong>{u.name}{u.id===user.id?' · '+t('您','You'):''}</strong><small>{u.email} · {u.projects} {t('件作品','works')}</small></span><select aria-label={`${u.email} ${t('權限','role')}`} value={u.role} disabled={!!busy} onChange={e=>void role(u.id,e.target.value)}><option value="user">{t('使用者','User')}</option><option value="admin">{t('管理員','Admin')}</option></select></div>)}</div>}
 {tab==='works'&&<div className="admin-rows">{data.works.filter(matches).map((p:any)=><div key={p.id}><span><strong>{p.title}</strong><small>{p.ownerName} · {p.ownerEmail} · v{p.version}</small></span><button onClick={()=>onOpen(p.id)}>{t('檢視作品','View work')}</button></div>)}</div>}</>}
 </div>;
}
