import {useRef,useState} from 'react';
import {Paperclip,Send,X,FileText,LoaderCircle} from 'lucide-react';
import {record} from './diagnostics';
type Props={locale:string,base:string,projectId:string,draft:string,onDraft:(s:string)=>void,files:any[],onFiles:(f:any[])=>void,selected:string[],onSelected:(ids:string[])=>void,disabled:boolean,busy:boolean,api:(url:string,method?:string,body?:any)=>Promise<any>,onSend:()=>void,onError:(e:any)=>void};
export function ChatComposer({locale,base,projectId,draft,onDraft,files,onFiles,selected,onSelected,disabled,busy,api,onSend,onError}:Props){
 const t=(zh:string,en:string)=>locale==='en'?en:zh,input=useRef<HTMLInputElement>(null),textarea=useRef<HTMLTextAreaElement>(null),[uploading,setUploading]=useState(false),[drag,setDrag]=useState(false),[caret,setCaret]=useState(0),[choice,setChoice]=useState(0),[dismissed,setDismissed]=useState(false);
 const match=draft.slice(0,caret).match(/(?:^|\s)@([^\s@]*)$/u),available=files.filter(f=>!f.archived),suggestions=match&&!dismissed?available.filter(f=>`${f.name} ${f.mention}`.toLowerCase().includes(match[1].toLowerCase())).slice(0,8):[];
 function mention(file:any){const start=caret-(match?.[1].length||0)-1,next=draft.slice(0,start)+'@'+file.mention+' '+draft.slice(caret);onDraft(next);onSelected([...new Set([...selected,file.id])]);setDismissed(true);requestAnimationFrame(()=>{textarea.current?.focus();textarea.current?.setSelectionRange(start+file.mention.length+2,start+file.mention.length+2);});}
 async function upload(incoming:FileList|File[]){if(disabled||uploading)return;const list=Array.from(incoming);if(list.length>12){onError(Error('referenceTooMany'));return;}const target=projectId;setUploading(true);let ids=[...selected];try{for(const file of list){const data=new FormData();data.append('file',file);const updated=await api(`/projects/${target}/references`,'POST',data);onFiles(updated);const created=updated.at(-1);if(created)ids.push(created.id);onSelected([...new Set(ids)]);record('info','reference.upload.complete',{projectId:target,bytes:file.size,type:file.type});}}catch(e){onError(e);}finally{setUploading(false);input.current&&(input.current.value='');}}
 return <div className={'reference-composer '+(drag?'drag-over':'')} onDragOver={e=>{if(!disabled&&e.dataTransfer.types.includes('Files')){e.preventDefault();setDrag(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(false);}} onDrop={e=>{e.preventDefault();setDrag(false);if(!disabled)void upload(e.dataTransfer.files);}}>
 <input hidden ref={input} type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.md,.csv,.json,.xml,.musicxml,.mxl" onChange={e=>{if(e.target.files)void upload(e.target.files);}}/>
 {selected.length>0&&<div className="reference-chips">{selected.map(id=>{const f=files.find(f=>f.id===id);return f&&<span key={id}><FileText size={12}/><a href={`${base}/api/references/${id}`} download>{f.name}</a><button disabled={disabled} aria-label={t('取消附加','Detach')+' '+f.name} onClick={()=>onSelected(selected.filter(x=>x!==id))}><X size={12}/></button></span>;})}</div>}
 <div className="composer-box"><textarea ref={textarea} disabled={disabled} aria-label={t('AI 聊天訊息','AI chat message')} placeholder={t('描述編曲，輸入 @ 引用檔案…','Describe your arrangement; type @ to reference a file…')} value={draft} onChange={e=>{onDraft(e.target.value);setCaret(e.target.selectionStart);setChoice(0);setDismissed(false);}} onSelect={e=>setCaret(e.currentTarget.selectionStart)} onKeyDown={e=>{if(suggestions.length){if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setChoice((choice+(e.key==='ArrowDown'?1:-1)+suggestions.length)%suggestions.length);}if(['Enter','Tab'].includes(e.key)){e.preventDefault();mention(suggestions[Math.min(choice,suggestions.length-1)]);}if(e.key==='Escape')setDismissed(true);}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&draft.trim()&&!busy&&!uploading){e.preventDefault();onSend();}}}/>
 {suggestions.length>0&&<ul role="listbox" aria-label={t('參考檔案建議','Reference suggestions')} className="mention-menu">{suggestions.map((f,i)=><li key={f.id} role="option" aria-selected={i===choice}><button onMouseDown={e=>e.preventDefault()} onClick={()=>mention(f)}><FileText size={14}/><span>@{f.mention}</span></button></li>)}</ul>}
 <div><button type="button" title={t('上傳參考檔案或拖曳至此','Upload references or drop files here')} aria-label={t('上傳參考檔案','Upload reference files')} disabled={disabled||uploading} onClick={()=>input.current?.click()}>{uploading?<LoaderCircle size={16} className="spin"/>:<Paperclip size={16}/>}</button><span>{uploading?t('準備參考檔案…','Preparing references…'):drag?t('放開以上傳','Drop to upload'):t('@ 引用 · 拖曳上傳','@ references · drop files')}</span><button aria-label={t('傳送訊息','Send message')} disabled={disabled||!draft.trim()||busy||uploading} onClick={onSend}><Send size={16}/></button></div></div>
 {available.length>0&&<details className="reference-library"><summary>{t('聊天參考檔案','Chat references')} ({available.length})</summary>{available.map(f=><div key={f.id}><label><input type="checkbox" disabled={disabled} checked={selected.includes(f.id)} onChange={e=>onSelected(e.target.checked?[...selected,f.id]:selected.filter(id=>id!==f.id))}/><span>@{f.mention}</span></label><a href={`${base}/api/references/${f.id}`} download>{t('下載','Download')}</a></div>)}</details>}
 <small className="reference-help">{t('每個檔案 12 MB；PDF 最多 12 頁。勾選的檔案與 @ 引用會提供給 AI。','12 MB per file; up to 12 PDF pages. Selected and @-mentioned files are sent to AI.')}</small>
 </div>;
}
