import {playbackBars,expandRepeats} from '../shared/repeats';
import {secondsAt} from './audio';
import {useEffect,useLayoutEffect,useRef,useState,useMemo,memo} from 'react';
import createVerovioModule from 'verovio/wasm';
import {VerovioToolkit} from 'verovio/esm';
import {type Score,toMusicXML,barTicks} from '../shared/music';
import type {BarSelection} from '../shared/edit-scope';
let modulePromise:Promise<any>|undefined;
const ScorePage=memo(({svg}:{svg:string})=><div className="score-sheet" dangerouslySetInnerHTML={{__html:svg}}/>);
export async function renderScore(score:Score,underlay=true):Promise<string[]>{modulePromise??=createVerovioModule();const toolkit=new VerovioToolkit(await modulePromise);try{toolkit.setOptions({inputFrom:'musicxml',pageWidth:2100,pageHeight:2970,scale:40,adjustPageHeight:true,breaks:'auto',header:'auto',footer:'none',font:'Leipzig',fontTextLiberation:true,svgViewBox:true});if(!toolkit.loadData(toMusicXML(score,underlay)))throw Error('notationFailed');return Array.from({length:toolkit.getPageCount()},(_,i)=>toolkit.renderToSVG(i+1));}finally{toolkit.destroy();}}
type Props={score:Score,underlay?:boolean,fit?:boolean,onSelect:(id:string)=>void,onPages:(pages:string[])=>void,range?:BarSelection|null,onRange?:(range:BarSelection)=>void,selectBars?:boolean,playback?:{position:number,playing:boolean,follow:boolean}};
export function ScoreView({score,onSelect,onPages,range,onRange,selectBars=false,playback,underlay=false,fit=false}:Props){const [pages,setPages]=useState<string[]>([]),[error,setError]=useState(''),host=useRef<HTMLDivElement>(null),anchor=useRef<number|null>(null),dragging=useRef(false),lastScroll=useRef(0),highlighted=useRef<SVGGElement[]>([]);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{renderScore(score,underlay).then(p=>{if(live){setPages(p);onPages(p);setError('');}}).catch(error=>{console.error('score.render.failed',error);if(live)setError('無法顯示樂譜 / Score rendering failed');});},120);return()=>{live=false;clearTimeout(timer);};},[score,underlay]);
 useEffect(()=>{const end=()=>{dragging.current=false;};addEventListener('pointerup',end);addEventListener('pointercancel',end);return()=>{removeEventListener('pointerup',end);removeEventListener('pointercancel',end);};},[]);
 useEffect(()=>{host.current?.querySelectorAll<SVGGElement>('.measure').forEach((g,index)=>{g.querySelectorAll('.bar-range-highlight').forEach(r=>r.remove());g.classList.toggle('bar-selectable',selectBars);if(range&&index+1>=range.startBar&&index+1<=range.endBar){const box=g.getBBox(),rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('class','bar-range-highlight');rect.setAttribute('x',String(box.x-20));rect.setAttribute('y',String(box.y-40));rect.setAttribute('width',String(box.width+40));rect.setAttribute('height',String(box.height+80));rect.setAttribute('fill','#70b28f');rect.setAttribute('fill-opacity','.25');g.insertBefore(rect,g.firstChild);}});},[pages,range?.startBar,range?.endBar,selectBars]);
 const timing=useMemo(()=>{const bt=barTicks(score),expanded=expandRepeats(score),bars=playbackBars(score);return bars.flatMap((bar,i)=>score.parts.flatMap(p=>p.notes.filter(n=>n.pitch!==null&&n.start<bar*bt&&n.start+n.duration>(bar-1)*bt).map(n=>{const start=Math.max(n.start,(bar-1)*bt),end=Math.min(n.start+n.duration,bar*bt),tied=start>n.start||['stop','continue'].includes(n.tie);return {id:n.id+(tied?'-t'+(bar-1):''),start:secondsAt(expanded,i*bt+start-(bar-1)*bt),end:secondsAt(expanded,i*bt+end-(bar-1)*bt),lead:p.id===score.leadId};})));},[score]);
 useLayoutEffect(()=>{if(!playback?.playing||!host.current){for(const g of highlighted.current)g.classList.remove('playing-note');highlighted.current=[];return;}const previous=highlighted.current;highlighted.current=[];const active=timing.filter(n=>n.start<=playback.position&&playback.position<n.end);let target:SVGGElement|null=null;for(const note of active){const g=host.current.querySelector<SVGGElement>('#'+CSS.escape(note.id));if(g){g.classList.add('playing-note');highlighted.current.push(g);if(!target||note.lead)target=g;}}for(const g of previous)if(!highlighted.current.includes(g))g.classList.remove('playing-note');if(playback.follow&&target&&performance.now()-lastScroll.current>650){const bounds=target.getBoundingClientRect(),container=host.current.closest('.score-canvas')?.getBoundingClientRect(),top=Math.max(0,container?.top||0),bottom=Math.min(innerHeight,container?.bottom||innerHeight),left=Math.max(0,container?.left||0),right=Math.min(innerWidth,container?.right||innerWidth);if(bounds.top<top+30||bounds.bottom>bottom-30||bounds.left<left+30||bounds.right>right-30){lastScroll.current=performance.now();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center',inline:'center'});}}},[playback?.position,playback?.playing,playback?.follow,timing,pages]);
 useEffect(()=>{const resize=()=>host.current?.querySelectorAll<SVGSVGElement>('.score-sheet > svg').forEach(svg=>{svg.style.minWidth='';(svg.parentElement as HTMLElement).style.minWidth='';if(fit)return;let min=Infinity;for(const el of svg.querySelectorAll<SVGGraphicsElement>('text,tspan')){if(!Array.from(el.childNodes).some(n=>n.nodeType===Node.TEXT_NODE&&n.textContent?.trim()))continue;const matrix=el.getScreenCTM(),font=parseFloat(getComputedStyle(el).fontSize);if(matrix&&font>0)min=Math.min(min,font*Math.hypot(matrix.a,matrix.b));}if(min>0&&min<11.95){const width=Math.ceil(svg.getBoundingClientRect().width*12/min);svg.style.minWidth=width+'px';(svg.parentElement as HTMLElement).style.minWidth=(width+40)+'px';}});const frame=requestAnimationFrame(resize),observer=new ResizeObserver(resize);if(host.current)observer.observe(host.current);return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[pages,fit]);
 function bar(target:EventTarget){const g=(target as Element).closest('.measure');return g?Array.from(host.current?.querySelectorAll('.measure')||[]).indexOf(g)+1:0;}
 return <><nav className="score-page-navigation" aria-label="Score pages / 樂譜頁面"><label>頁 / Page <select aria-label="Go to page / 前往頁面" defaultValue="" onChange={e=>{host.current?.querySelectorAll('.score-sheet')[Number(e.target.value)]?.scrollIntoView({block:'start'});e.target.value='';}}><option value="" disabled>1–{pages.length||1}</option>{pages.map((_,i)=><option key={i} value={i}>{i+1} / {pages.length}</option>)}</select></label><span>↕ 捲動瀏覽全譜 / Scroll for the full score</span></nav><div ref={host} className={'score-pages '+(selectBars?'selecting-bars':'')} onPointerDown={e=>{if(!selectBars)return;const n=bar(e.target);if(!n)return;e.preventDefault();anchor.current=e.shiftKey&&range?range.startBar:n;dragging.current=true;onRange?.({startBar:Math.min(anchor.current,n),endBar:Math.max(anchor.current,n)});}} onPointerOver={e=>{if(!selectBars||!dragging.current||anchor.current===null)return;const n=bar(e.target);if(n)onRange?.({startBar:Math.min(anchor.current,n),endBar:Math.max(anchor.current,n)});}} onClick={e=>{if(selectBars)return;const n=(e.target as Element).closest('.note');if(n?.id)onSelect(n.id.replace(/-t\d+$/,''));}}>{error&&<p role="alert">{error}</p>}{pages.map((svg,i)=><ScorePage key={i} svg={svg}/>)}{!pages.length&&!error&&<div className="score-loading">♪</div>}</div></>;
}


