import {secondsAt} from './audio';
import {useEffect,useRef,useState,useMemo} from 'react';
import createVerovioModule from 'verovio/wasm';
import {VerovioToolkit} from 'verovio/esm';
import {type Score,toMusicXML,barTicks} from '../shared/music';
import type {BarSelection} from '../shared/edit-scope';
let modulePromise:Promise<any>|undefined;
export async function renderScore(score:Score):Promise<string[]>{modulePromise??=createVerovioModule();const toolkit=new VerovioToolkit(await modulePromise);try{toolkit.setOptions({inputFrom:'musicxml',pageWidth:2100,pageHeight:2970,scale:40,adjustPageHeight:true,breaks:'auto',header:'auto',footer:'none',font:'Leipzig',fontTextLiberation:true,svgViewBox:true});if(!toolkit.loadData(toMusicXML(score,true)))throw Error('notationFailed');return Array.from({length:toolkit.getPageCount()},(_,i)=>toolkit.renderToSVG(i+1));}finally{toolkit.destroy();}}
type Props={score:Score,onSelect:(id:string)=>void,onPages:(pages:string[])=>void,range?:BarSelection|null,onRange?:(range:BarSelection)=>void,selectBars?:boolean,playback?:{position:number,playing:boolean,follow:boolean}};
export function ScoreView({score,onSelect,onPages,range,onRange,selectBars=false,playback}:Props){const [pages,setPages]=useState<string[]>([]),[error,setError]=useState(''),host=useRef<HTMLDivElement>(null),anchor=useRef<number|null>(null),dragging=useRef(false),lastScroll=useRef(0),highlighted=useRef<SVGGElement[]>([]);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{renderScore(score).then(p=>{if(live){setPages(p);onPages(p);setError('');}}).catch(error=>{console.error('score.render.failed',error);if(live)setError('無法顯示樂譜 / Score rendering failed');});},120);return()=>{live=false;clearTimeout(timer);};},[score]);
 useEffect(()=>{const end=()=>{dragging.current=false;};addEventListener('pointerup',end);addEventListener('pointercancel',end);return()=>{removeEventListener('pointerup',end);removeEventListener('pointercancel',end);};},[]);
 useEffect(()=>{host.current?.querySelectorAll<SVGGElement>('.measure').forEach((g,index)=>{g.querySelectorAll('.bar-range-highlight').forEach(r=>r.remove());g.classList.toggle('bar-selectable',selectBars);if(range&&index+1>=range.startBar&&index+1<=range.endBar){const box=g.getBBox(),rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('class','bar-range-highlight');rect.setAttribute('x',String(box.x-20));rect.setAttribute('y',String(box.y-40));rect.setAttribute('width',String(box.width+40));rect.setAttribute('height',String(box.height+80));rect.setAttribute('fill','#70b28f');rect.setAttribute('fill-opacity','.25');g.insertBefore(rect,g.firstChild);}});},[pages,range?.startBar,range?.endBar,selectBars]);
 const timing=useMemo(()=>{const bt=barTicks(score);return score.parts.flatMap(p=>p.notes.filter(n=>n.pitch!==null).flatMap(n=>{const segments=[];for(let b=Math.floor(n.start/bt);b*bt<n.start+n.duration;b++){const tied=b*bt>n.start||['stop','continue'].includes(n.tie);segments.push({id:n.id+(tied?'-t'+b:''),start:secondsAt(score,Math.max(n.start,b*bt)),end:secondsAt(score,Math.min(n.start+n.duration,(b+1)*bt)),lead:p.id===score.leadId});}return segments;}));},[score]);
 useEffect(()=>{for(const g of highlighted.current)g.classList.remove('playing-note');highlighted.current=[];if(!playback?.playing||!host.current)return;const active=timing.filter(n=>n.start<=playback.position&&playback.position<n.end);let target:SVGGElement|null=null;for(const note of active){const g=host.current.querySelector<SVGGElement>('#'+CSS.escape(note.id));if(g){g.classList.add('playing-note');highlighted.current.push(g);if(!target||note.lead)target=g;}}if(playback.follow&&target&&performance.now()-lastScroll.current>650){const bounds=target.getBoundingClientRect(),container=host.current.closest('.score-canvas')?.getBoundingClientRect(),top=Math.max(0,container?.top||0),bottom=Math.min(innerHeight,container?.bottom||innerHeight),left=Math.max(0,container?.left||0),right=Math.min(innerWidth,container?.right||innerWidth);if(bounds.top<top+30||bounds.bottom>bottom-30||bounds.left<left+30||bounds.right>right-30){lastScroll.current=performance.now();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center',inline:'center'});}}},[playback?.position,playback?.playing,playback?.follow,timing,pages]);
 useEffect(()=>{const resize=()=>host.current?.querySelectorAll<SVGSVGElement>('.score-sheet > svg').forEach(svg=>{let min=Infinity;for(const el of svg.querySelectorAll<SVGGraphicsElement>('text,tspan')){if(!Array.from(el.childNodes).some(n=>n.nodeType===Node.TEXT_NODE&&n.textContent?.trim()))continue;const matrix=el.getScreenCTM(),font=parseFloat(getComputedStyle(el).fontSize);if(matrix&&font>0)min=Math.min(min,font*Math.hypot(matrix.a,matrix.b));}if(min>0&&min<11.95)svg.style.minWidth=Math.ceil(svg.getBoundingClientRect().width*12/min)+'px';});const frame=requestAnimationFrame(resize),observer=new ResizeObserver(resize);if(host.current)observer.observe(host.current);return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[pages]);
 function bar(target:EventTarget){const g=(target as Element).closest('.measure');return g?Array.from(host.current?.querySelectorAll('.measure')||[]).indexOf(g)+1:0;}
 return <><nav className="score-page-navigation" aria-label="Score pages / 樂譜頁面"><label>頁 / Page <select aria-label="Go to page / 前往頁面" defaultValue="" onChange={e=>{host.current?.querySelectorAll('.score-sheet')[Number(e.target.value)]?.scrollIntoView({block:'start'});e.target.value='';}}><option value="" disabled>1–{pages.length||1}</option>{pages.map((_,i)=><option key={i} value={i}>{i+1} / {pages.length}</option>)}</select></label><span>↕ 捲動瀏覽全譜 / Scroll for the full score</span></nav><div ref={host} className={'score-pages '+(selectBars?'selecting-bars':'')} onPointerDown={e=>{if(!selectBars)return;const n=bar(e.target);if(!n)return;e.preventDefault();anchor.current=e.shiftKey&&range?range.startBar:n;dragging.current=true;onRange?.({startBar:Math.min(anchor.current,n),endBar:Math.max(anchor.current,n)});}} onPointerOver={e=>{if(!selectBars||!dragging.current||anchor.current===null)return;const n=bar(e.target);if(n)onRange?.({startBar:Math.min(anchor.current,n),endBar:Math.max(anchor.current,n)});}} onClick={e=>{if(selectBars)return;const n=(e.target as Element).closest('.note');if(n?.id)onSelect(n.id.replace(/-t\d+$/,''));}}>{error&&<p role="alert">{error}</p>}{pages.map((svg,i)=><div className="score-sheet" key={i} dangerouslySetInnerHTML={{__html:svg}}/>)}{!pages.length&&!error&&<div className="score-loading">♪</div>}</div></>;
}
