import {playbackBars,expandRepeats} from '../shared/repeats';
import {secondsAt} from './audio';
import {useEffect,useLayoutEffect,useRef,useState,useMemo,memo} from 'react';
import createVerovioModule from 'verovio/wasm';
import {VerovioToolkit} from 'verovio/esm';
import {type Score,toMusicXML,barTicks,notationScore} from '../shared/music';
import type {BarSelection} from '../shared/edit-scope';
let modulePromise:Promise<any>|undefined;
const ScorePage=memo(({svg}:{svg:string})=><div className="score-sheet" dangerouslySetInnerHTML={{__html:svg}}/>);
export async function renderScore(score:Score,underlay=true,layout?:{width:number,zoom:number}):Promise<string[]>{modulePromise??=createVerovioModule();const toolkit=new VerovioToolkit(await modulePromise);try{const scale=layout?Math.max(1,Math.round(.4*layout.zoom)):40;toolkit.setOptions({inputFrom:'musicxml',pageWidth:layout?Math.max(100,Math.round(layout.width*100/scale)):2100,pageHeight:2970,scale,adjustPageHeight:true,breaks:'auto',header:'auto',footer:'none',font:'Leipzig',fontTextLiberation:true,svgViewBox:true});if(!toolkit.loadData(toMusicXML(score,underlay)))throw Error('notationFailed');return Array.from({length:toolkit.getPageCount()},(_,i)=>toolkit.renderToSVG(i+1));}finally{toolkit.destroy();}}
type Props={score:Score,underlay?:boolean,fit?:boolean,onSelect:(id:string)=>void,onPages:(pages:string[])=>void,range?:BarSelection|null,onRange?:(range:BarSelection)=>void,selectBars?:boolean,playback?:{position:number,playing:boolean,follow:boolean}};
export function ScoreView({score,onSelect,onPages,range,onRange,selectBars=false,playback,underlay=false,fit=false}:Props){const [zoom,setZoom]=useState(100),[zoomInput,setZoomInput]=useState('100'),[width,setWidth]=useState(0);const [pages,setPages]=useState<string[]>([]),[error,setError]=useState(''),host=useRef<HTMLDivElement>(null),anchor=useRef<number|null>(null),dragging=useRef(false),lastScroll=useRef(0),highlighted=useRef<SVGGElement[]>([]);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{renderScore(score,underlay,width?{width,zoom}:undefined).then(p=>{if(live){setPages(p);onPages(p);setError('');}}).catch(error=>{console.error('score.render.failed',error);if(live)setError('無法顯示樂譜 / Score rendering failed');});},120);return()=>{live=false;clearTimeout(timer);};},[score,underlay,width,zoom]);
 useEffect(()=>{const end=()=>{dragging.current=false;};addEventListener('pointerup',end);addEventListener('pointercancel',end);return()=>{removeEventListener('pointerup',end);removeEventListener('pointercancel',end);};},[]);
 useEffect(()=>{host.current?.querySelectorAll<SVGGElement>('.measure').forEach((g,index)=>{g.querySelectorAll('.bar-range-highlight').forEach(r=>r.remove());g.classList.toggle('bar-selectable',selectBars);if(range&&index+1>=range.startBar&&index+1<=range.endBar){const box=g.getBBox(),rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('class','bar-range-highlight');rect.setAttribute('x',String(box.x-20));rect.setAttribute('y',String(box.y-40));rect.setAttribute('width',String(box.width+40));rect.setAttribute('height',String(box.height+80));rect.setAttribute('fill','#70b28f');rect.setAttribute('fill-opacity','.25');g.insertBefore(rect,g.firstChild);}});},[pages,range?.startBar,range?.endBar,selectBars]);
 const timing=useMemo(()=>{const bt=barTicks(score),expanded=expandRepeats(score),bars=playbackBars(score),notated=notationScore(score);return bars.flatMap((bar,i)=>notated.parts.flatMap(p=>p.notes.filter(n=>n.pitch!==null&&n.start<bar*bt&&n.start+n.duration>(bar-1)*bt).map(n=>{const start=Math.max(n.start,(bar-1)*bt),end=Math.min(n.start+n.duration,bar*bt),tied=start>n.start||['stop','continue'].includes(n.tie);return {id:n.id+(tied?'-t'+(bar-1):''),start:secondsAt(expanded,i*bt+start-(bar-1)*bt),end:secondsAt(expanded,i*bt+end-(bar-1)*bt),lead:p.id===score.leadId};})));},[score]);
 useLayoutEffect(()=>{if(!playback?.playing||!host.current){for(const g of highlighted.current)g.classList.remove('playing-note');highlighted.current=[];return;}const previous=highlighted.current;highlighted.current=[];const active=timing.filter(n=>n.start<=playback.position&&playback.position<n.end);let target:SVGGElement|null=null;for(const note of active){const g=host.current.querySelector<SVGGElement>('#'+CSS.escape(note.id));if(g){g.classList.add('playing-note');highlighted.current.push(g);if(!target||note.lead)target=g;}}for(const g of previous)if(!highlighted.current.includes(g))g.classList.remove('playing-note');if(playback.follow&&target){
  const container=host.current.closest<HTMLElement>('.score-canvas'),system=target.closest<SVGGElement>('.system');
  if(container&&system){

   const viewport=container.getBoundingClientRect(),top=Math.max(0,viewport.top,host.current.previousElementSibling?.getBoundingClientRect().bottom||0),bottom=Math.min(innerHeight,viewport.bottom);
   if(performance.now()-lastScroll.current>650){const bounds=system.getBoundingClientRect(),note=target.getBoundingClientRect();const dy=bounds.top<top+16||bounds.bottom>bottom-16?bounds.top-top-16:0,dx=note.left<viewport.left+20||note.right>viewport.right-20?(note.left+note.right-viewport.left-viewport.right)/2:0;
    if(Math.abs(dy)>1||Math.abs(dx)>1){lastScroll.current=performance.now();container.scrollBy({top:dy,left:dx,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
   }
  }
 }},[playback?.position,playback?.playing,playback?.follow,timing,pages,zoom]);
 useLayoutEffect(()=>{const element=host.current;if(!element)return;const resize=()=>{const sheet=element.querySelector<HTMLElement>('.score-sheet'),style=sheet?getComputedStyle(sheet):null,inset=style?parseFloat(style.paddingLeft)+parseFloat(style.paddingRight)+2:38;setWidth(Math.max(100,Math.floor(element.clientWidth-inset)));};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect();},[pages.length]);
 function changeZoom(value:number){const next=Math.max(25,Math.min(200,Math.round(value)||100));setZoom(next);setZoomInput(String(next));}
 function bar(target:EventTarget){const g=(target as Element).closest('.measure');return g?Array.from(host.current?.querySelectorAll('.measure')||[]).indexOf(g)+1:0;}
 return <><nav className="score-page-navigation" aria-label="Score pages / 樂譜頁面"><div className="score-zoom"><label>Zoom / 縮放 <input aria-label="Score zoom percent / 樂譜縮放百分比" type="number" min={25} max={200} value={zoomInput} onChange={e=>setZoomInput(e.target.value)} onBlur={()=>changeZoom(Number(zoomInput))} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>%</label><input aria-label="Score zoom / 樂譜縮放" type="range" min={25} max={200} step={5} value={zoom} onChange={e=>changeZoom(Number(e.target.value))}/><button onClick={()=>changeZoom(100)}>100%</button></div><label>頁 / Page <select aria-label="Go to page / 前往頁面" defaultValue="" onChange={e=>{host.current?.querySelectorAll('.score-sheet')[Number(e.target.value)]?.scrollIntoView({block:'start'});e.target.value='';}}><option value="" disabled>1–{pages.length||1}</option>{pages.map((_,i)=><option key={i} value={i}>{i+1} / {pages.length}</option>)}</select></label><span>↕ 捲動瀏覽全譜 / Scroll for the full score</span></nav><div ref={host} className={'score-pages '+(selectBars?'selecting-bars':'')} onPointerDown={e=>{if(!selectBars)return;const n=bar(e.target);if(!n)return;e.preventDefault();anchor.current=e.shiftKey&&range?range.startBar:n;dragging.current=true;onRange?.({startBar:Math.min(anchor.current,n),endBar:Math.max(anchor.current,n)});}} onPointerOver={e=>{if(!selectBars||!dragging.current||anchor.current===null)return;const n=bar(e.target);if(n)onRange?.({startBar:Math.min(anchor.current,n),endBar:Math.max(anchor.current,n)});}} onClick={e=>{if(selectBars)return;const n=(e.target as Element).closest('.note');if(n?.id)onSelect(n.id.replace(/-t\d+$/,'').replace(/-s\d+$/,''));}}>{error&&<p role="alert">{error}</p>}{pages.map((svg,i)=><ScorePage key={i} svg={svg}/>)}{!pages.length&&!error&&<div className="score-loading">♪</div>}</div></>;
}
