import {useEffect,useState} from 'react';
import {Download,Trash2,LoaderCircle,CheckCircle2,Music2} from 'lucide-react';
import {useLiveEvent} from './live';
import {filterVoices} from '../shared/voice-filter';
import {record} from './diagnostics';
import {VoiceImportPanel} from './VoiceImportPanel';
type Props={locale:string,api:(url:string,method?:string,body?:any)=>Promise<any>,onChange:(banks:any[])=>void};
const mb=(bytes:number)=>`${((bytes||0)/1024/1024).toFixed(1)} MB`;
export function VoicebankManager({locale,api,onChange}:Props){
 const t=(zh:string,en:string)=>locale==='en'?en:zh;
 const [state,setState]=useState<any>(null),[error,setError]=useState(''),[working,setWorking]=useState(''),[query,setQuery]=useState(''),[language,setLanguage]=useState(''),[status,setStatus]=useState(''),[source,setSource]=useState(''),[compatibility,setCompatibility]=useState('');
 const update=(s:any)=>{setState(s);onChange(s.banks.filter((b:any)=>b.installable!==false));setError('');};useLiveEvent('voicebanks',update);
 useEffect(()=>{let active=true;void api('/voicebanks').then(s=>{if(active)update(s);}).catch(()=>{if(active)setError(t('無法載入聲庫。請重新開啟聲庫管理員。','Could not load the catalog. Reopen the voicebank manager.'));});return()=>{active=false;};},[]);
 const banks=state?.banks||[],shown=filterVoices(banks,query,language,status).filter(b=>(!source||b.source===source)&&(!compatibility||b.compatibility===compatibility)),languages=[...new Set<string>(banks.flatMap((b:any)=>b.languageCodes||[]))];
 useEffect(()=>{record('debug','voicebank.filter',{queryLength:query.length,language,status,total:banks.length,matches:shown.length});},[query,language,status,banks.length]);
 async function change(id:string,method:string){setWorking(id);setError('');try{update(await api(`/voicebanks/${encodeURIComponent(id)}`,method,{}));}catch(e:any){setError(e.message==='voiceInUse'?t('此聲庫正在合成中，完成或取消合成後即可移除。','This voice is rendering. Finish or cancel it before removal.'):e.message==='voiceBusy'?t('請等待目前的下載完成，或先取消。','Wait for the current download or cancel it first.'):t('操作失敗，請重試。','The action failed. Please retry.'));}finally{setWorking('');}}
 return <><div className="eyebrow">CHOIRLOOM VOICE LIBRARY</div><h2>{t('共用聲庫','Shared voice library')}</h2><p className="muted small">{t('瀏覽多個發布者的聲庫，並依語言、來源及安裝狀態篩選。可用聲庫皆經過實際演唱測試；管理員也可從公開網址匯入新聲庫。','Browse and filter voices from multiple publishers. Available voices have passed actual singing tests; admins can also import new public packages.')}</p>
 <div className="library-summary"><span>{banks.length} {t('款聲庫','voices')} · {banks.filter((b:any)=>b.status==='installed').length} {t('款已下載','downloaded')}</span><strong>{mb(state?.storageBytes)}</strong></div>
 {state?.canManage&&<VoiceImportPanel locale={locale} imports={state.imports||[]} api={api} onChange={update}/>}
 <div className="library-filters"><input aria-label={t('搜尋聲庫','Search voices')} placeholder={t('名稱、語言或聲部，例如：波音リツ、日文、alto','Name, language or range: Ritsu, Japanese, alto')} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={t('語言篩選','Filter language')} value={language} onChange={e=>setLanguage(e.target.value)}><option value="">{t('所有語言','All languages')}</option>{languages.map(l=><option key={l} value={l}>{{en:t('英文','English'),zh:t('中文','Chinese'),ja:t('日文','Japanese'),yue:t('粵語','Cantonese'),th:t('泰文','Thai'),fr:t('法文','French'),de:t('德文','German'),ko:t('韓文','Korean'),es:t('西班牙文','Spanish'),pt:t('葡萄牙文','Portuguese'),ru:t('俄文','Russian'),it:t('義大利文','Italian'),pl:t('波蘭文','Polish'),fil:t('菲律賓文','Filipino'),id:t('印尼文','Indonesian'),vi:t('越南文','Vietnamese')}[l]||l}</option>)}</select><select aria-label={t('來源篩選','Filter publisher')} value={source} onChange={e=>setSource(e.target.value)}><option value="">{t('所有來源','All publishers')}</option>{[...new Set<string>(banks.map((b:any)=>b.source))].map(v=><option key={v}>{v}</option>)}</select><select aria-label={t('相容性篩選','Filter compatibility')} value={compatibility} onChange={e=>setCompatibility(e.target.value)}><option value="">{t('所有相容性','All compatibility')}</option><option value="verified">{t('可在 Choirloom 使用','Ready for Choirloom')}</option><option value="publisher">{t('發布者下載','Publisher downloads')}</option><option value="permission">{t('需要創作者許可','Creator permission required')}</option></select></div>
 <div className="library-tabs">{[['',t('全部','All')],['downloadable',t('可下載','Available to download')],['installed',t('已下載','Downloaded')],['downloading',t('下載中','Downloading')]].map(([v,label])=><button key={v} className={status===v?'selected':''} onClick={()=>setStatus(v)}>{label}</button>)}</div>
 {error&&<p role="alert" className="library-error">{error}</p>}{state?.catalogError&&<p role="alert" className="library-error">{t('聲庫目錄載入失敗，管理員可在診斷紀錄查看原因。','The catalog could not load. Administrators can inspect diagnostics.')}</p>}
 {!state&&!error&&<p role="status"><LoaderCircle className="spin" size={16}/> {t('載入聲庫…','Loading voices…')}</p>}
 <div className="voicebank-catalog">{shown.map((b:any)=><article className="voicebank-entry" key={b.id}><div className="voicebank-title"><span className="voicebank-icon"><Music2/></span><div><h3>{b.displayName?.[locale]||b.name}</h3><small>{b.version} · {b.languages.join(' / ')} · {b.installable?mb(b.downloadBytes):b.source}</small></div>{b.status==='installed'&&<CheckCircle2 size={20}/>}</div><p>{typeof b.description==='object'?b.description[locale]||b.description.en:b.description}</p><div className="voicebank-license"><span>{b.attribution}</span><a href={b.licenseUrl} target="_blank" rel="noreferrer">{t('使用條款','Voice license')} ↗</a></div>
 {b.status==='downloading'&&<div className="voicebank-progress" role="status"><progress max="100" value={b.progress}/><span>{t('下載與解壓縮中','Downloading & extracting')} {b.progress}%</span></div>}{b.status==='failed'&&<p className="library-error">{t('下載未完成，可重試或移除部分檔案。','Download did not finish. Retry or remove the partial files.')}</p>}
 <div className="voicebank-actions">{!b.installable&&<a className="button primary" href={b.availabilityReason?b.licenseUrl:b.downloadUrl||b.sourceUrl} target="_blank" rel="noreferrer">{b.availabilityReason?t('查看使用條款','View usage terms'):t('發布者下載頁面','Publisher downloads')} ↗</a>}{!b.installable&&<small>{b.availabilityReason?t('需要創作者許可','Creator permission required'):t('尚不可在 Choirloom 合成','Not yet renderable in Choirloom')}</small>}{b.installable&&!['installed','downloading'].includes(b.status)&&<button className="primary" disabled={!!working} onClick={()=>void change(b.id,'POST')}><Download size={15}/>{b.status==='failed'?t('重試下載','Retry download'):t('下載聲庫','Download voice')}</button>}{b.installable&&state.canManage&&b.status!=='available'&&<button disabled={!!working} onClick={()=>void change(b.id,'DELETE')}>{working===b.id?<LoaderCircle className="spin" size={15}/>:<Trash2 size={15}/>} {b.status==='downloading'?t('取消下載','Cancel download'):t('移除下載','Remove download')}</button>}{b.status==='installed'&&<small>{t('已就緒，可於聲部選用','Ready · select in a voice part')} · {mb(b.bytes)}</small>}</div>{b.downloads?.length>0&&<details><summary>{t('下載檔案','Download files')} ({b.downloads.length})</summary>{b.downloads.map((f:any)=><p key={f.url}><a href={f.url} target="_blank" rel="noreferrer">{f.name}</a> · {mb(f.bytes)}</p>)}</details>}{b.checkedAt&&<small>{t('來源檢查日期','Source checked')}: {b.checkedAt}</small>}</article>)}
 {state&&!shown.length&&!state.catalogError&&<div className="library-empty"><Music2/><h3>{banks.length?t('沒有符合篩選條件的聲音','No voices match these filters'):t('目前目錄沒有聲庫','The catalog has no voices yet')}</h3><p>{t('「可下載」不包含已安裝的聲庫。','Available to download excludes voices already installed.')}</p>{banks.length>0&&<button onClick={()=>{setQuery('');setLanguage('');setStatus('');setSource('');setCompatibility('');}}>{t('清除篩選，瀏覽全部聲庫','Clear filters and show all voices')}</button>}</div>}</div>
 <p className="muted small">{t('安裝於 Choirloom 的聲庫由所有使用者共用，僅管理員可移除。發布者連結的檔案下載至本站之外。此目錄持續維護，並非網路所有聲庫的完整索引。','Voices installed in Choirloom are shared by everyone; only admins can remove them. Publisher links download outside Choirloom. This is a maintained directory, not an exhaustive index of every voice on the internet.')}</p></>;
}
