import {useState} from 'react';
import {Download,LoaderCircle} from 'lucide-react';

export function VoiceImportPanel({locale,imports,api,onChange}:{locale:string,imports:any[],api:(url:string,method?:string,body?:any)=>Promise<any>,onChange:(state:any)=>void}){
 const t=(zh:string,en:string)=>locale==='en'?en:zh;
 const empty={name:'',publisher:'',url:'',licenseUrl:'',configuration:'',vocoderUrl:''};
 const [form,setForm]=useState(empty),[working,setWorking]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false);
 const labels:Record<string,string>={queued:t('準備中','Queued'),downloading:t('下載中','Downloading'),inspecting:t('檢查套件','Inspecting package'),inspected:t('套件檢查完成','Package inspected'),validating:t('驗證模型','Validating models'),rendering:t('測試歌詞及無詞演唱','Testing lyrics and wordless singing'),installing:t('安裝共用聲庫','Installing shared voice'),completed:t('已安裝並共用','Installed for everyone'),failed:t('匯入失敗','Import failed'),interrupted:t('已中斷，可重試','Interrupted · retry available')};
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setWorking(true);try{onChange(await api('/voicebanks/import','POST',{...form,configuration:form.configuration||undefined,vocoderUrl:form.vocoderUrl||undefined}));setForm(empty);}catch(e:any){setError(e.message==='voiceBusy'?t('請等待目前的聲庫作業或合成完成。','Wait for the current voice operation or rendering to finish.'):e.message);}finally{setWorking(false);}}
 return <section className="voice-import"><details open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{t('從網址匯入新聲庫（管理員）','Import a new voice from a URL (admin)')}</summary><p>{t('提供公開的 DiffSinger ONNX ZIP 下載網址或 Google Drive 分享連結。完成模型檢查及實際演唱測試後，聲庫才會開放給所有使用者。','Provide a public DiffSinger ONNX ZIP URL or Google Drive share link. The voice becomes available to everyone after model validation and an actual singing test.')}</p><form onSubmit={e=>void submit(e)}><div className="voice-import-fields">{([['name',t('聲庫名稱','Voice name')],['publisher',t('發布者／署名','Publisher / attribution')],['url',t('公開下載網址','Public download URL')],['licenseUrl',t('發布者使用條款網址','Publisher license URL')]] as const).map(([key,label])=><label key={key}>{label}<input required type={key.endsWith('Url')||key==='url'?'url':'text'} maxLength={key.endsWith('Url')||key==='url'?2048:120} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><details><summary>{t('進階相容性選項','Advanced compatibility options')}</summary><label>{t('套件內的 dsconfig.yaml 路徑（選填）','dsconfig.yaml path inside package (optional)')}<input value={form.configuration} onChange={e=>setForm({...form,configuration:e.target.value})}/></label><label>{t('發布者 ONNX 聲碼器 ZIP 網址（選填）','Publisher ONNX vocoder ZIP URL (optional)')}<input type="url" value={form.vocoderUrl} onChange={e=>setForm({...form,vocoderUrl:e.target.value})}/></label></details><p className="muted small">{t('保留原始模型及授權檔；使用時須遵守發布者條款。訓練用 checkpoint 或傳統 UTAU 音源無法直接匯入。','Original models and notices are preserved; publisher terms apply. Training checkpoints and traditional UTAU sample banks cannot be imported directly.')}</p><button className="primary" disabled={working||imports.some(i=>i.status==='running'&&i.stage!=='cleanup-failed')}>{working?<LoaderCircle size={16} className="spin"/>:<Download size={16}/>} {t('匯入、測試並安裝','Import, test and install')}</button>{error&&<p role="alert" className="library-error">{error}</p>}</form></details>
 {imports.length>0&&<div className="voice-import-history">{imports.map(item=><article key={item.id}><strong>{item.request.name}</strong><p role={item.status==='running'?'status':undefined}>{item.status==='running'&&<LoaderCircle className="spin" size={14}/>} {labels[item.stage]||item.stage}{item.stage==='downloading'?` · ${item.progress}%`:''}</p>{item.error&&<p className="library-error">{item.error}</p>}{item.report?.choices&&<details><summary>{t('已偵測的模型設定','Detected model configurations')}</summary>{item.report.choices.map((c:any)=><p key={c.dsConfig}><code>{c.dsConfig}</code> · {c.embeddedVocoder?t('內建聲碼器','Embedded vocoder'):c.vocoder}{(item.status==='failed'||item.stage==='cleanup-failed')&&<button onClick={()=>{setForm({...empty,...item.request,configuration:c.dsConfig});setOpen(true);}}>{t('使用此設定重試','Retry with this configuration')}</button>}</p>)}</details>}{item.status==='completed'&&item.report?.verification&&<small>{t('實際演唱驗證完成；暫存檔已清除。','Actual singing verified; temporary files cleaned.')}</small>}{(item.status==='failed'||item.stage==='cleanup-failed')&&<button onClick={()=>{setForm({...empty,...item.request});setOpen(true);}}>{t('編輯並重試','Edit and retry')}</button>}</article>)}</div>}</section>;
}
